### ISSUE TITLE
Modulenotfound error

### ISSUE THREAD

**Issue by studenttubs** [KratosMultiphysics/Kratos#10030]
Hey Kratos-Team,

after finally adding the PFemApplication to my interface and kratos i tried to run the dambreak example. 
when i try to run it, both command shell or GiD i get the following error:
C:\Users\J. Kremer (SA. HvH)\Documents\examples\example 2\Pfem example\neuesbeispiel.gid>python mainkratos.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.1."2"-de953cb-Release
Compiled with threading support.
Maximum number of threads: 16.
Traceback (most recent call last):
  File "C:\Users\J. Kremer (SA. HvH)\Documents\examples\example 2\Pfem example\neuesbeispiel.gid\mainkratos.py", line 40, in <module>
    analysis_stage_module = importlib.import_module(analysis_stage_module_name)
  File "C:\Users\J. Kremer (SA. HvH)\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'KratosMultiphysics.PfemFluidDynamicsApplication
Its running on windows with python 3.9.

Can someone help me fixing the issue? 

Thank you and best regards

Johanna

**Comment by studenttubs** [comment]
Hey @jginternational 

I used pip install

**Comment by jginternational** [comment]
Unfortunately, PFEM Application is not deployed via pip
You will need to build Kratos from source, or maybe @AFranci can send you a compiled version.

Follow this manual to build for windows
https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md#windows-installation

**Comment by Geo-Jia** [comment]
Hey Kratos-Team,

I have encountered the same issue. I build PfemFluidDynamicsApplication from source under a Linux system. How can I resolve this problem?

Thank you and best regards

Shilin

**Comment by AFranci** [comment]
Hi @Geo-Jia 

As we discussed last week, your problem is not related to PfemFuidDynamicsApplication but is more general, as you cannot reproduce even the basic Kratos test. More likely, your issue is due to incorrect settings for the environmental variables.

Regards,

Alessandro

**Comment by jginternational** [comment]
Hi @Geo-Jia 
I understand you are using GiD to generate and run your cases.
Could you attach a screenshot of your settings?

In GiD, with kratos loaded, go to Utilities > Preferences > Kratos
Since you build from source, you should set 'Your compiled Kratos'
I need to see the setting below

**Comment by Geo-Jia** [comment]
Hi @jginternational 
This is a screenshot of my settings. All of them are the default values. With these settings, structural problems in Kratos can run successfully, but the PFEM problems cannot.

<img width="1707" height="907" alt="Image" src="https://github.com/user-attachments/assets/e6e9393a-2ad5-4103-82a8-973cb0bb6dcb" />

**Comment by Geo-Jia** [comment]
> Hi [@Geo-Jia](https://github.com/Geo-Jia)
> 
> As we discussed last week, your problem is not related to PfemFuidDynamicsApplication but is more general, as you cannot reproduce even the basic Kratos test. More likely, your issue is due to incorrect settings for the environmental variables.
> 
> Regards,
> 
> Alessandro

Hi @AFranci 

I have set the  the environmental variables follow the Wiki, as shown in the attachment. The basic Kratos test suggested in the Wiki runs successfully. However, it still doesn’t work for my case.

<img width="1637" height="1164" alt="Image" src="https://github.com/user-attachments/assets/cac11359-2f2a-41d4-9012-e7e0f06ef988" />

<img width="1617" height="1234" alt="Image" src="https://github.com/user-attachments/assets/74676b52-ec34-4269-bf05-b6daeab102a7" />

**Comment by jginternational** [comment]
Ok, I can see the problem here @Geo-Jia 

The default settings in GiD are "Use the pip packages and the GiD Python interpreter"
PFEM apps are not available via pip install.

Instead, you should change the preferences > Launch configuration to 'Your compiled Kratos'

Then fill the options: 

- python path to the python binary (you can use which python3 on a shell)
- kratos path: route to your installed kratos, I can see in the pic that it's /home/jiager/Kratos/bin/Release
