### ISSUE TITLE
[Biomedical] Test Case Randomly Failing

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10115]
I've seen ```testUnitParabolaString2D``` randomly fail in the CI with the same message a couple of times now. It failed on Windows most recently, but it might not be limited to that platform. Here's the traceback from the CI:
```
 FAIL: testUnitParabolaString2D (apply_parabolic_inlet_process_test.ApplyParabolicInletProcessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\Kratos\Kratos\bin\Custom\applications\FluidDynamicsBiomedicalApplication\tests\apply_parabolic_inlet_process_test.py", line 180, in testUnitParabolaString2D
    self.assertVectorAlmostEqual(test_node.GetSolutionStepValue(KratosMultiphysics.VELOCITY), [0.0,2.0,0.0])
  File "D:\a\Kratos\Kratos\bin\Custom\KratosMultiphysics\KratosUnittest.py", line 92, in assertVectorAlmostEqual
    self.assertAlmostEqual(v1, v2, places, LazyErrMsg(i, msg), delta)
AssertionError: 0.0 != 2.0 within 7 places (2.0 difference) : 
Check failed because vector arguments are not equal in component 1
Vector 1:
[3](-0,0,-0)
Vector 2:
[0.0, 2.0, 0.0]
```

@rubenzorrilla can you please look into it?

**Comment by mpentek** [comment]
Noticed it by chance with the tests for this PR as well  #10101

**Comment by roigcarlo** [comment]
After some investigation, it looks to me that the problem is related with the `function_parser_utility`.

In the `parabolic_profile_utilities.cpp` there is a block of code:

```C++
// Impose the parabolic profile values
    block_for_each(rModelPart.Nodes(), array_1d<double,3>(), [time, max_dist, MaxValueFactor, &rMaxParabolaValue](NodeType& rNode, array_1d<double,3>& rTLSValue){
        //Calculate distance for each node
        const double wall_dist = rNode.GetValue(WALL_DISTANCE) < 0.0 ? 0.0 : rNode.GetValue(WALL_DISTANCE);

        // Calculate the inlet direction
        rTLSValue = rNode.GetValue(INLET_NORMAL);

        const double n_norm = norm_2(rTLSValue);
        if (n_norm > 1.0e-12) {
            rTLSValue /= -n_norm;
        } else {
            KRATOS_WARNING("ImposeParabolicProfile") << "Node " << rNode.Id() << " INLET_NORMAL is close to zero." << std::endl;
            rTLSValue /= -1.0;
        }

        // Calculate the inlet value module
        const double max_value = MaxValueFactor * GetMaxParabolaValue(time, rNode, rMaxParabolaValue);
        const double value_in = max_value * (1.0-(std::pow(max_dist-wall_dist,2)/std::pow(max_dist,2)));
        rTLSValue *= value_in;

        // Set and fix the VELOCITY DOFs
        rNode.FastGetSolutionStepValue(VELOCITY) = rTLSValue;
        rNode.Fix(VELOCITY_X);
        rNode.Fix(VELOCITY_Y);
        rNode.Fix(VELOCITY_Z);
    });
```

Which is is a parallel region but is calling the `GetMaxParabolaValue`, which takes `rMaxParabolaValue` as a ref pointer (the problem is the pointer) to the function evaluator.

But the function evaluator stores the calling values inside a member:

```C++
double BasicGenericFunctionUtility::CallFunction(
    const double x,
    const double y,
    const double z,
    const double t,
    const double X,
    const double Y,
    const double Z
    )
{
    mValues[0] = x;
    mValues[1] = y;
    mValues[2] = z;
    mValues[3] = t;
    mValues[4] = X;
    mValues[5] = Y;
    mValues[6] = Z;
```

Which is causing making it to fail randomly

We should pass the function inside the TLS or make a local copy. Also ping @KratosMultiphysics/technical-committee because this means that generic functions are not threadsafe and this is VERY dangerous.
