### ISSUE TITLE
[ShallowWater] Failing Tests

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10444]
@KratosMultiphysics/shallow-water I'm sure you've noticed by now that```TestBoussinesq2D3NElement``` from ```ShallowWaterApplication``` fails in the CI pretty frequently. Is anyone working on solving this?

Here's the traceback for reference:
```
======================================================================
FAIL: test_execution (shallow_water_test_factory.TestBoussinesq2D3NElement)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Custom/applications/ShallowWaterApplication/tests/shallow_water_test_factory.py", line 23, in test_execution
    test.Run()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 150, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/from_json_check_result_process.py", line 51, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable HEIGHT, results:
Node 1 -nan!=1.014807; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 19 -nan!=1.039735; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 2 -nan!=1.025515; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 20 -nan!=1.081385; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 3 -nan!=1.025515; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 21 -nan!=1.056985; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 4 -nan!=1.040619; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 22 -nan!=1.056985; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 5 -nan!=1.035727; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 23 -nan!=1.015463; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 6 -nan!=1.035727; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 24 -nan!=1.05713; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 7 -nan!=1.05713; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 25 -nan!=1.05713; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 8 -nan!=1.05713; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 26 -nan!=1.015463; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 9 -nan!=1.081385; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 27 -nan!=1.024357; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 10 -nan!=1.035526; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 28 -nan!=1.024357; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 11 -nan!=1.035526; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 29 -nan!=1.035526; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 12 -nan!=1.056985; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 30 -nan!=1.035526; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 13 -nan!=1.056985; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 31 -nan!=1.040619; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 14 -nan!=1.081435; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 32 -nan!=1.035727; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 15 -nan!=1.081435; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 33 -nan!=1.035727; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 16 -nan!=1.024357; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 34 -nan!=1.025515; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 17 -nan!=1.024357; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 35 -nan!=1.025515; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 18 -nan!=1.039735; rel_tol=1e-06, abs_tol=1e-06
Error checking for variable HEIGHT, results:
Node 36 -nan!=1.014807; rel_tol=1e-06, abs_tol=1e-06
```

**Comment by miguelmaso** [comment]
> @KratosMultiphysics/shallow-water I'm sure you've noticed by now that`TestBoussinesq2D3NElement` from `ShallowWaterApplication` fails in the CI pretty frequently. Is anyone working on solving this?

I find it difficult to debug since it fails randomly with clang and I don't have time. However, I'm very interested on this element, depending on the incoming projects, I would need it.

Given my situation, I'll disable the test by now.
