### ISSUE TITLE
Issue with Self contact example

### ISSUE THREAD

**Issue by danielesavio** [KratosMultiphysics/Kratos#11314]
Dear all,

I am getting started with Kratos, and am currently facing an issue / bug when trying to simulate the example case "Self contact" provided here: https://kratosmultiphysics.github.io/Examples/contact_structural_mechanics/use_cases/self_contact/

I am using the latest Kratos Version (9.3) in this environment:
- OS: Windows
- Branch: master
- Python 3.9.12 
- Installed with pip into Anaconda

When trying to run the example, I get the following error message:
```
> ALM Values: The potential parameters for penalty and scale factor are:
> PENALTY SLAVE:  8.16817e+13     PENALTY MASTER: 8.16817e+13
> SCALE FACTOR SLAVE:     8.16817e+13     SCALE FACTOR MASTER:    8.16817e+13
> SCALE_FACTOR: : 8.17e+13
> INITIAL_PENALTY: : 8.17e+13
> 
> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\self_contact\MainKratos.py", line 19, in <module>
>     simulation.Run()
>   File "C:\Users\user\anaconda3\lib\site-packages\KratosMultiphysics\analysis_stage.py", line 47, in Run
>     self.Initialize()
>   File "C:\Users\user\anaconda3\lib\site-packages\KratosMultiphysics\StructuralMechanicsApplication\structural_mechanics_analysis.py", line 42, in Initialize
>     super().Initialize()
>   File "C:\Users\user\anaconda3\lib\site-packages\KratosMultiphysics\analysis_stage.py", line 91, in Initialize
>     process.ExecuteInitialize()
>   File "C:\Users\user\anaconda3\lib\site-packages\KratosMultiphysics\ContactStructuralMechanicsApplication\alm_contact_process.py", line 203, in ExecuteInitialize
>     super().ExecuteInitialize()
>   File "C:\Users\user\anaconda3\lib\site-packages\KratosMultiphysics\ContactStructuralMechanicsApplication\search_base_process.py", line 201, in ExecuteInitialize
>     self.search_utility_list[key].ExecuteInitialize()
> RuntimeError: Error: mPointListDestination not initialized
> 
> 
> 
> 
> in kratos/applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp:1044: BaseContactSearchProcess<3,3,3>::FillPointListDestination
>    kratos/applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp:1046: BaseContactSearchProcess<3,3,3>::FillPointListDestination
>    kratos/applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp:432: BaseContactSearchProcess<3,3,3>::CreatePointListMortar
>    kratos/applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp:175: BaseContactSearchProcess<3,3,3>::ExecuteInitialize
```

Before that, the reading of the simulation parameters, CL and .mdpa file all seem correct. 
Am I missing something? Could you look into this issue?

Thank you in advance,
and best regards

Daniele Savio

**Comment by AlejandroCornejo** [comment]
Hi! just to confirm, you just downloaded the input data and tried to run it right? AFAIK the self contact is still under development and not properly tested.

Let's see if @loumalouomega has an idea about what's happening :)

**Comment by AlejandroCornejo** [comment]
I am interested in self contact too, I can help in this issue too once we know Vicente's opinion

**Comment by loumalouomega** [comment]
The strange thing is that the same example is used as a nightly test..., should fail as well. Maybe I need to check. Self-contact in Kratos is not perfect, but at least that test should work.

**Comment by loumalouomega** [comment]
I don't have plenty of time, so I don't know when I will be able to check it. Sorry
