### ISSUE TITLE
[SwimmingDem] Chien Drag Test Analysis Failing in Nightly

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#11931]
**Description**
@jgonzalezusua Seems that `chien_drag_test_analysis.py` is causing the nightly build to fail. Could you take a look?
Pinging you because we have no one assigned to Swimming dem and the test was last touched by you 3 months ago.

Sample of the failing report: https://github.com/KratosMultiphysics/Kratos/actions/runs/7447864857/job/20261002872?pr=11930

```
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/SwimmingDEMApplication/tests/DragTestFactory.py", line 26, in test_execution
    self.test.Run()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/SwimmingDEMApplication/swimming_DEM_analysis.py", line 205, in Run
    super().Run()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 50, in Run
    self.Finalize()
  File "/__w/Kratos/Kratos/bin/Release/applications/SwimmingDEMApplication/tests/drag_tests/chien_law/chien_drag_test_analysis.py", line 34, in Finalize
    self.CheckValues(x_vel)
UnboundLocalError: local variable 'x_vel' referenced before assignment
```

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/dem @jgonzalezusua is this still active?
