### ISSUE TITLE
[DEM] DEMEraseParticlesWithDelay Failing in CI

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#11954]
**Description**
@KratosMultiphysics/dem  Seems that `test_erase_particles_with_delay.py` is causing the some builds to fail. Could you take a look?

Sample of the failing report: https://github.com/KratosMultiphysics/Kratos/actions/runs/7500737454/job/20420045725

```
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Custom/applications/DEMApplication/tests/test_erase_particles.py", line 51, in test_erase_particles_with_delay
    self.RunTest(project_parameters_file_name, expected_number_of_particles)
  File "/__w/Kratos/Kratos/bin/Custom/applications/DEMApplication/tests/test_erase_particles.py", line 61, in RunTest
    analysis.Run()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.Initialize()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/DEMApplication/DEM_analysis_stage.py", line 251, in Initialize
    self.SetMaterials()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/DEMApplication/DEM_analysis_stage.py", line 316, in SetMaterials
    materials_setter.AssignPropertiesToEntities()
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/DEMApplication/materials_assignation_utility.py", line 61, in AssignPropertiesToEntities
    for smp in submodelpart.SubModelParts:
MemoryError: std::bad_alloc
```

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/dem @roigcarlo is this solved?

**Comment by roigcarlo** [comment]
No, ping again @KratosMultiphysics/dem

**Comment by ChengshunShang1996** [comment]
Sorry for the delay. I will take a look.
