### ISSUE TITLE
Bug on multiple cuts

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#1997]
Hi! 
I'm trying to set more than one cut plane for a CFD and having an error

```
Traceback (most recent call last):
  File "MainKratos.py", line 58, in <module>
    gid_output.ExecuteInitialize()
  File "E:\GiD\GiD 14.0-rc1\problemtypes\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 129, in ExecuteInitialize
    self.__initialize_cut_output(plane_output_configuration)
  File "E:\GiD\GiD 14.0-rc1\problemtypes\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 361, in __initialize_cut_output
    self.__define_output_plane(cut_data)
  File "E:\GiD\GiD 14.0-rc1\problemtypes\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 455, in __define_output_plane
    0.01)
RuntimeError: Error: attempting to add the variable: FATHER_NODES to the model part with name: CutPart which is not empty


in kratos/includes/model_part.h:472:ModelPart::AddNodalSolutionStepVariable
   kratos/utilities/cutting_utility.h:184:CuttingUtility::GenerateCut
```

[Example case attached](https://we.tl/H0hnNYPj1P)

**Comment by jcotela** [comment]
Thanks for the report, I'll take a look.

**Comment by jcotela** [comment]
Looks like we were doing some rather dangerous things with the model part's nodal variables in the current implementation, which were silently allowed before but fail with an error now. I'll try to figure out a workaround.
