### ISSUE TITLE
Problem importing Kratos

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#2010]
Hi, I am working in branch master and I am not able to import Kratos. The python script is:

~~~
from KratosMultiphysics import *
from KratosMultiphysics.MeshingApplication import *
from KratosMultiphysics.FluidDynamicsApplication import *

Tester.SetVerbosity(Tester.Verbosity.TESTS_LIST)

Tester.RunTestSuite("KratosCoreGeometriesFastSuite")

Tester.RunTestSuite("FluidDynamicsApplicationFastSuite")

Tester.RunTestSuite("MeshingApplicationFastSuite")
~~~

And the output:
~~~
mmaso@PCCB019:~/Escritorio$ python3 run_tests.py 
Traceback (most recent call last):
  File "run_tests.py", line 1, in <module>
    from KratosMultiphysics import *
  File "/home/mmaso/Kratos/KratosMultiphysics/__init__.py", line 13, in <module>
    from Kratos import *
ImportError: /home/mmaso/Kratos/libs/Kratos.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN6Kratos9ModelPartC1ERKS0_
~~~

I have tried deleting libs folder and recompiling...

**Comment by roigcarlo** [comment]
@miguelmaso Looks like the python version you are using to compile is not the same as the one called by pytho3. 

Can you paste the config file?

**Comment by miguelmaso** [comment]
It is the same config file I was using yesterday...

~~~
#!/bin/sh

# this is an example file...please DO NOT MODIFY if you don't want to do it for everyone
#to use it, copy it to another file and run it

# additional compiler flags could be added customizing the corresponding var, for example
# -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 ". Note that the "defaults are already correctly coded"
#so we should ass here only machine specific stuff

#an effort is made to autodetect all of the libraries needed HOWEVER:
#METIS_APPLICATION needs the var PARMETIS_ROOT_DIR to be specified by the user (not needed if the app is set to OFF)
#TRILINOS_APPLICATION needs the var PARMETIS_ROOT_DIR to be specified by the user (not needed if the app is set to OFF)
#MKL_SOLVERS_APPLICATION needs the var MKLSOLVER_INCLUDE_DIR and MKLSOLVER_LIB_DIR to be specified by the user (not needed if the app is set to OFF)
#note that the MKLSOLVER_LIB_DIR should include /lib/em64t. This is needed as intel is changing location of mkl at every update of the compiler!!

#the user should also note that the symbol "\" marks that the command continues on the next line. IT SHOULD ONLY BE FOLLOWED
#BY the "ENTER" and NOT by any space!!

clear

#you may want to decomment this the first time you compile
rm CMakeCache.txt
rm *.cmake
rm -rf CMakeFiles\

cmake ..                                                                            \
-DCMAKE_C_COMPILER=/usr/bin/gcc                                                     \
-DCMAKE_INSTALL_RPATH="/home/mmaso/Kratos/libs"                                     \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE                                            \
-DCMAKE_CXX_COMPILER=/usr/bin/g++                                                   \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 "                           \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 "                                          \
-DBOOST_PYTHON_SUFFIX="-py35"                                                       \
-DPYTHON_LIBRARY="/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so" \
-DPYTHON_INCLUDE_DIR="/usr/include/python3.5"                                       \
-DPYTHON_EXECUTABLE="/usr/bin/python3"                                              \
-DCMAKE_BUILD_TYPE=Release                                                          \
-DKRATOS_BUILD_TESTING=ON                                                           \
-DMESHING_APPLICATION=ON                                                            \
-DEXTERNAL_SOLVERS_APPLICATION=OFF                                                  \
-DSTRUCTURAL_MECHANICS_APPLICATION=OFF                                              \
-DCONVECTION_DIFFUSION_APPLICATION=OFF                                              \
-DSOLID_MECHANICS_APPLICATION=OFF                                                   \
-DCONSTITUTIVE_MODELS_APPLICATION=OFF                                               \
-DFLUID_DYNAMICS_APPLICATION=ON                                                     \
-DALE_APPLICATION=OFF                                                               \
-DFSI_APPLICATION=OFF                                                               \
-DDEM_APPLICATION=OFF                                                               \
-DSWIMMING_DEM_APPLICATION=OFF                                                      \
-DMIXED_ELEMENT_APPLICATION=OFF                                                     \
-DSHALLOW_WATER_APPLICATION=OFF                                                     \
-DSHAPE_OPTIMIZATION_APPLICATION=OFF                                                \
-DTOPOLOGY_OPTIMIZATION_APPLICATION=OFF                                             \
-DMETIS_APPLICATION=OFF                                                             \
-DPARMETIS_ROOT_DIR="/home/youruser/compiled_libraries/ParMetis-3.1.1"              \
-DTRILINOS_APPLICATION=OFF                                                          \
-DTRILINOS_ROOT="/home/youruser/compiled_libraries/trilinos-10.2.0"                 \
-DINSTALL_EMBEDDED_PYTHON=ON

#decomment this to have it verbose
# make VERBOSE=1 -j4
make -j2
make install
~~~

**Comment by roigcarlo** [comment]
Everything looks good, try to remove:

```
-DBOOST_PYTHON_SUFFIX="-py35"                                                       \
-DPYTHON_LIBRARY="/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so" \
-DPYTHON_INCLUDE_DIR="/usr/include/python3.5"                                       \
```

They are no longer needed and may cause problems

**Comment by miguelmaso** [comment]
Thanks for your support @roigcarlo 
There was a problem with the version of the master.
I have pulled the master and recompiled it, now I can import Kratos
