### ISSUE TITLE
[StructuralMechanics] errors in tests related to ResponseFunctions

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2022]
From the nightly report:

compiler warning:
~~~
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h:342:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
~~~

test errors:
~~~
======================================================================
ERROR: test_execution (structural_response_function_test_factory.TestMassResponseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py", line 74, in test_execution
    self.assertAlmostEqual(self.value, 1569.9999999999998)
  File "/usr/lib/python3.5/unittest/case.py", line 861, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

Stdout:
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/response_function_tests

======================================================================
ERROR: test_execution (structural_response_function_test_factory.TestStrainEnergyResponseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py", line 85, in test_execution
    self.assertAlmostEqual(self.value, 8.484005297318718e-05)
  File "/usr/lib/python3.5/unittest/case.py", line 861, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

Stdout:
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/tests/response_function_tests
~~~

**Comment by armingeiser** [comment]
I'll have a look.
