### ISSUE TITLE
Some tests are failing in Windows

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#2170]
6 tests are failing on my local windows build from today. I copied the output below:
@philbucher maybe you know who i should assign here?

```
======================================================================
ERROR: test_model_part_io_write_model_part (test_model_part_io.TestModelPartIO)
----------------------------------------------------------------------
Traceback (most recent call last):  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_model_part_io.py", line 24, in tearDown    kratos_utils.DeleteFileIfExisting(GetFilePath("test_model_part_io_write.out.mdpa"))  File "F:/05_Software/Windows/KratosInstall/Kratos36\KratosMultiphysics\kratos_utilities.py", line 22, in DeleteFileIfExisting    os.remove(file_name)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'F:\\05_Software\\Windows\\KratosInstall\\Kratos36\\kratos\\tests\\test_model_part_io_write.out.mdpa'

======================================================================
FAIL: test_model_part_io_write_model_part (test_model_part_io.TestModelPartIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_model_part_io.py", line 171, in test_model_part_io_write_model_part
    self.assertEqual(value, True)
AssertionError: False != True

======================================================================
FAIL: test_gid_io_all (test_gid_io.TestGidIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_gid_io.py", line 90, in test_gid_io_all
    self.__Check("all_active_out_0.post.msh","all_active_ref.ref")
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_gid_io.py", line 83, in __Check
    cmp_process.ExecuteFinalize()
  File "F:\04_Development\Kratos\kratos\python_scripts\compare_two_files_check_process.py", line 74, in ExecuteFinalize
    self.assertTrue(value)
AssertionError: False is not true

======================================================================
FAIL: test_gid_io_deactivation (test_gid_io.TestGidIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_gid_io.py", line 103, in test_gid_io_deactivation
    self.__Check("deactivated_out_0.post.msh","deactivated_ref.ref")
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_gid_io.py", line 83, in __Check
    cmp_process.ExecuteFinalize()
  File "F:\04_Development\Kratos\kratos\python_scripts\compare_two_files_check_process.py", line 74, in ExecuteFinalize
    self.assertTrue(value)
AssertionError: False is not true

======================================================================
FAIL: test_gid_io_results (test_gid_io.TestGidIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_gid_io.py", line 159, in test_gid_io_results
    self.__Check("results_out_0.post.res","results_out_ref.ref")
  File "F:\05_Software\Windows\KratosInstall\Kratos36\kratos\tests\test_gid_io.py", line 83, in __Check
    cmp_process.ExecuteFinalize()
  File "F:\04_Development\Kratos\kratos\python_scripts\compare_two_files_check_process.py", line 74, in ExecuteFinalize
    self.assertTrue(value)
AssertionError: False is not true


======================================================================
    TestModelPartSubModelPartsIterator Failed with message:
        Error:  node index not found: 2.
in kratos/includes/mesh.h:274:Mesh<class Node<3,class Dof >,class Properties,class Element,class Condition>::GetNode

```

**Comment by roigcarlo** [comment]
@philbucher First one is a known problem, it happens from time to time in win. 
Basically it tries to delte a file that is being used by some other process, but I still trying to understand why since should be freed by the time the tearDown is called.. As for the others no idea.

**Comment by pooyan-dadvand** [comment]
@roigcarlo does these tests fail also for you?

**Comment by roigcarlo** [comment]
As I told to @philbucher, The iterator test was failing but that is already fixed. I cannot reproduce the others.

**Comment by roigcarlo** [comment]
Btw, the `test_model_part_io_write_model_part` error is related with #1741. It should be solved, if it still crashes because a file is open chances are that the file is acutally open by some folder / editor / process etc or the modelpart is creating some other file, but again, it seems to work fine in my win.

**Comment by pooyan-dadvand** [comment]
I could not reproduce it. @armingeiser does it still giving error for you?

**Comment by armingeiser** [comment]
I will test it next time i am booting on Windows.

**Comment by armingeiser** [comment]
The iterator test is fixed for me too, however I still get the 4 io test errors.
But if I am the only one getting them, I think i can close this Issue. The errors do not seem to affect my daily work.
