### ISSUE TITLE
[StructuralMechanics] problem with membrane

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2295]
Some of the membrane tests are failing atm after #2101 

~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Fofi4PointTentnoCableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 156, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != 0.07986688763000538, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 4 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Fofi4PointTentCableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 156, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != -0.03131864022032899, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 2 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.MembraneQ4PointLoadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 156, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != -0.473612074593017, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 4 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.MembraneQ4TrussPointLoadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 156, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != -0.037499751604797626, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 4 DISPLACEMENT_Z results.
~~~

fyi @inigolcanalejo @longchentum

**Comment by philbucher** [comment]
@annasophie91 [your commit](https://github.com/KratosMultiphysics/Kratos/pull/2101/commits/b32787a28b92c22b00e8d4f2fd017eb24007f221) broke it, can you please have a look?

**Comment by philbucher** [comment]
![screenshot from 2018-06-10 13-46-47](https://user-images.githubusercontent.com/25484702/41201258-c539aab4-6cb4-11e8-9ecb-d648f9138f18.png)

**Comment by philbucher** [comment]
ping @annasophie91

**Comment by philbucher** [comment]
ping @annasophie91

**Comment by philbucher** [comment]
@annasophie91 is there any chance you will fix this?
