### ISSUE TITLE
[StructuralMechanics] Many errors in tests

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2631]
Guys we have many errors in the tests: 

@loumalouomega could those be related to the Stuff with the ConvergenceCriteria?

@armingeiser @MFusseder 
~~~
======================================================================
FAIL: test_execution (structural_response_function_test_factory.TestAdjointDisplacementResponseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py", line 95, in test_execution
    self.assertAlmostEqual(self.gradient[nodeId][0], 2046491212.095884, 12)
AssertionError: -1185105492.6252458 != 2046491212.095884 within 12 places

Stdout:
/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/response_function_tests

> Synchronize primal and adjoint modelpart for response: dummy

> Starting primal analysis for response: dummy
> Time needed for solving the primal analysis =  0.03 s
> Time needed for calculating the response value =  0.0 s

> Starting adjoint analysis for response: dummy
> Time needed for solving the adjoint analysis =  0.09 s

======================================================================
FAIL: test_execution (structural_response_function_test_factory.TestAdjointStressResponseFunction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py", line 108, in test_execution
    self.assertAlmostEqual(self.gradient[nodeId][0], -0.4522249114784208, 12)
AssertionError: -0.7975971438708829 != -0.4522249114784208 within 12 places

Stdout:
/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/response_function_tests

> Synchronize primal and adjoint modelpart for response: dummy

> Starting primal analysis for response: dummy
> Time needed for solving the primal analysis =  0.03 s
> Time needed for calculating the response value =  0.0 s

> Starting adjoint analysis for response: dummy
> Time needed for solving the adjoint analysis =  0.09 s

======================================================================
FAIL: test_CalculateSensitivityMatrix_Property (test_cr_beam_adjoint_element_3d2n.TestCrBeamAdjointElement)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_cr_beam_adjoint_element_3d2n.py", line 221, in test_CalculateSensitivityMatrix_Property
    self._assert_matrix_almost_equal(FDPseudoLoadMatrix, PseudoLoadMatrix, 7)
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_cr_beam_adjoint_element_3d2n.py", line 151, in _assert_matrix_almost_equal
    self.assertAlmostEqual(matrix1[i,j], matrix2[i,j], prec)
AssertionError: -154406571241.5613 != -154406571241.56128 within 7 places

======================================================================
FAIL: test_CalculateSensitivityMatrix_Shape (test_cr_beam_adjoint_element_3d2n.TestCrBeamAdjointElement)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_cr_beam_adjoint_element_3d2n.py", line 187, in test_CalculateSensitivityMatrix_Shape
    self._assert_matrix_almost_equal(FDPseudoLoadMatrix, PseudoLoadMatrix, 7)
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_cr_beam_adjoint_element_3d2n.py", line 151, in _assert_matrix_almost_equal
    self.assertAlmostEqual(matrix1[i,j], matrix2[i,j], prec)
AssertionError: 293161424.7178117 != 293161424.71781164 within 7 places

======================================================================
FAIL: test_local_stress_response (test_adjoint_sensitity_analysis_beam_3d2n_structure.TestAdjointSensitivityAnalysisBeamStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_adjoint_sensitity_analysis_beam_3d2n_structure.py", line 41, in test_local_stress_response
    self.assertAlmostEqual(sensitivities_to_check[0], reference_values[0], 5)
AssertionError: -87622.77094826999 != -87622.77099397512 within 5 places

======================================================================
FAIL: test_nodal_displacement_response (test_adjoint_sensitity_analysis_beam_3d2n_structure.TestAdjointSensitivityAnalysisBeamStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_adjoint_sensitity_analysis_beam_3d2n_structure.py", line 66, in test_nodal_displacement_response
    self.assertAlmostEqual(sensitivities_to_check[2], reference_values[2], 5)
AssertionError: -6.20030540009713 != -6.200311358415619 within 5 places

======================================================================
FAIL: test_strain_energy_response (test_adjoint_sensitity_analysis_beam_3d2n_structure.TestAdjointSensitivityAnalysisBeamStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_adjoint_sensitity_analysis_beam_3d2n_structure.py", line 87, in test_strain_energy_response
    self.assertAlmostEqual(sensitivities_to_check[0], reference_values[0], 5)
AssertionError: -9082.055906300393 != -9082.055913430777 within 5 places

----------------------------------------------------------------------


----------------------------------------------------------------------
~~~

---------------------------------------------------
@KlausBSautter 
~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Simple3D2NTrussLinearCompressionPlasticTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : -2.0833333333333464 != -1.0658141036401503e-14, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 1 REACTION_Y results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Simple3D2NTrussLinearTensionPlasticTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 2.0833333333333464 != 1.0658141036401503e-14, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 1 REACTION_Y results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Simple3D2NTrussNonLinearSnapthroughPlasticTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 288, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[gp]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking elem " + str(elem.Id) + " " + variable_name + " results."))
AssertionError: False is not true : [3](96.1608,0,0) != 96.15967831553421, rel_tol = 1e-06, abs_tol = 0.001 : Error checking elem 1 PK2_STRESS_VECTOR results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Simple3D2NTrussNonLinearTensionPlasticTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 245, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[gp]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking elem " + str(elem.Id) + " " + variable_name + " results."))
AssertionError: False is not true : [3](0.503738,0,0) != 0.5000002054294002, rel_tol = 1e-06, abs_tol = 0.001 : Error checking elem 1 FORCE results.
~~~

---------------------------------------------------
@inigolcanalejo 
~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Fofi4PointTentnoCableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != 0.07986688763000538, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 4 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Fofi4PointTentCableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != -0.03131864022032899, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 2 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.MembraneQ4PointLoadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != -0.473612074593017, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 4 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.MembraneQ4TrussPointLoadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 58, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 130, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0 != -0.037499751604797626, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 4 DISPLACEMENT_Z results.
~~~

---------------------------------------------------
@loumalouomega (this one is related to the ConvCritStuff I think)
~~~
test_execution (structural_mechanics_test_factory.SimpleMeshMovingTest) ... ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: WARNING:: ELEMENT ID: 1 INVERTED. DETJ0: -0.0264156



in /home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian.cpp:226:virtual void TotalLagrangian::CalculateKinematicVariables(BaseSolidElement::KinematicVariables&, TotalLagrangian::IndexType, const IntegrationMethod&)
   /home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian.cpp:210:virtual void TotalLagrangian::CalculateAll(Element::MatrixType&, Element::VectorType&, ProcessInfo&, bool, bool)
   kratos/solving_strategies/schemes/residual_based_implicit_time_scheme.h:258:void ResidualBasedImplicitTimeScheme<TSparseSpace, TDenseSpace>::Calculate_RHS_Contribution(Element::Pointer, ResidualBasedImplicitTimeScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType&, Element::EquationIdVectorType&, ProcessInfo&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; Element::Pointer = shared_ptr<Element>; ResidualBasedImplicitTimeScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Element::EquationIdVectorType = vector<long unsigned int>]

Aborted (core dumped)
~~~

**Comment by KlausBSautter** [comment]
why is this happening now ? Nothing changed from my side since everything was working the last time

**Comment by philbucher** [comment]
I don't know, but I have a suspicion

BTW I ran the tests only in Release

**Comment by philbucher** [comment]
guys I don't really know what is the reason, seems like the update of the convergence-criteria had some impact, but also without it some test are failing in my laptop

please investigate yourselves

**Comment by MFusseder** [comment]
I currently ran the tests on my machine. Thereby 8 tests failed. These were the membrane and nonlinear truss examples. All adjoint sensitivity analysis test cases work on my computer.

**Comment by philbucher** [comment]
@MFusseder thx for trying

might be numerical then :/
I will talk to you in person

**Comment by loumalouomega** [comment]
Before merging I run all the tests in full debug, the only ones failing were the ones related with the membrane, that have been failing since long time ago

**Comment by philbucher** [comment]
I digged into this for a few hours now and I think the change in the convergence criteria caused most of the issues

@armingeiser @MFusseder the failures in your tests seem to come from numerical precision, you compare very large values with a very small tolerance

@KlausBSautter in some tests that are failing the type is wrong (Vector != Double)
In the others you could try to decrease the tolerance of the convcrit and see if it works again

**Comment by philbucher** [comment]
In case you ask yourselves how I debugged:
I knew it was working ~3weeks ago, after this it started failing
Then I checked the major PRs that were merged in the meantime using 
~~~
git log --merges --first-parent master --pretty=format:"%H %<(10,trunc)%an %<(15)%ar %s"
~~~
To show when PRs were merged

Needless to say this is very time consuming :/

**Comment by KlausBSautter** [comment]
I guess I fixed it by decreasing the convergence tolerance. I hope we can soon make these tests compulsory to run before merging

**Comment by philbucher** [comment]
except the membrane tests everything is working now
