### ISSUE TITLE
Error runnning on windows

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#2724]
Hello I have compiled Kratos on windows ... no errors as I see in the visual studio output. 
followed the wiki post to copy all the .dll files into lib folder as mention and to test the installation I am running 

from KratosMultiphysics import *
import KratosMultiphysics.ExternalSolversApplication

this is giving me the following error : 

Multi-Physics 6.0.0-                                                                                         
Traceback (most recent call last):                                                                                        
File "test_kratos.py", line 2, in <module>
import KratosMultiphysics.ExternalSolversApplication                                                                  
File "E:\02_kratos_windows_installation\kratos_install\KratosMultiphysics\ExternalSolversApplication.py", line 2, in <module>                                                                                                                     
from KratosExternalSolversApplication import *                                                                      
ImportError: DLL load failed: %1 is not a valid Win32 application.                                                      
KRATOS TERMINATED WITH ERROR   

any ideas on how to solve this ? Is this a known issue ?

**Comment by adityaghantasala** [comment]
was using 32 bit libraries inplace of 64 bit ones .. using 64 bit ones solves the issue .. !
