### ISSUE TITLE
Error Tests StructuralMechanics

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2914]
the following test fails on my machine:
~~~
======================================================================
FAIL: test_Uniaxial_KirchhoffSaintVenant_3D (test_constitutive_law.TestConstitutiveLaw)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/test_constitutive_law.py", line 184, in test_Uniaxial_KirchhoffSaintVenant_3D
    self._generic_constitutive_law_test(model_part, deformation_test)
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/test_constitutive_law.py", line 176, in _generic_constitutive_law_test
    self.assertAlmostEqual(reference_stress[j], stress[j], 2)
AssertionError: 22265906249999.996 != 22265906250000.004 within 2 places
~~~

the error checking is too strict, I suggest changing the test such that a smaller stress will be the outcome

**Comment by loumalouomega** [comment]
This is clearly because using the assertAlmostEqual with absolute values instead of relative (and the tolerance is 2!!!!!)
