### ISSUE TITLE
[PfemFluid] Example Errors: Dam_Break_2D in PFEM

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3338]
Hello, everyone:
When I run the test, there are some errors, as followed:
Traceback (most recent call last):
  File "MainKratos.py", line 9, in <module>
    MainFluidPFEM.Solution().Run()
  File "/home/dongxueyang/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/MainFluidPFEM.py", line 101, in Run
    self.Initialize()
  File "/home/dongxueyang/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/MainFluidPFEM.py", line 159, in Initialize
    self.model_processes = process_handler.ProcessHandler(self.Model, process_parameters)
  File "/home/dongxueyang/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 35, in __init__
    self.Sort()
  File "/home/dongxueyang/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 116, in Sort
    self.list_of_processes += self.ConstructList( self.ProcessList(self.settings["problem_process_list"]) )
  File "/home/dongxueyang/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 177, in ConstructList
    unsorted_process_list.append(self.ConstructProcess(process))
  File "/home/dongxueyang/Kratos/applications/SolidMechanicsApplication/python_scripts/process_handler.py", line 165, in ConstructProcess
    kratos_module = __import__(process["kratos_module"].GetString())
  File "/home/dongxueyang/Kratos/KratosMultiphysics/PfemApplication.py", line 9, in <module>
    from KratosPfemApplication import *
ImportError: generic_type: type "SetActiveFlagProcess" is already registered!
KRATOS TERMINATED WITH ERROR
 I didn't find the problem in the input files. I think I have compiled the PFEM application correctly.
Any suggestions?

**Comment by AFranci** [comment]
The examples were obsolete. I have updated them, now they should be working

**Comment by philbucher** [comment]
Closing since inactive
