### ISSUE TITLE
[Core] MortarMapper test failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3468]
~~~
======================================================================
FAIL: test_mortar_mapping_quad (test_mortar_mapper.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/kratos/tests/test_mortar_mapper.py", line 164, in test_mortar_mapping_quad
    self._mapper_tests(input_filename, 4, 4)
  File "/home/philippb/software/Kratos_Master/kratos/tests/test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 154, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 10.04886216959597 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.

======================================================================
FAIL: test_mortar_mapping_quad_tri (test_mortar_mapper.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/kratos/tests/test_mortar_mapper.py", line 168, in test_mortar_mapping_quad_tri
    self._mapper_tests(input_filename, 4, 3)
  File "/home/philippb/software/Kratos_Master/kratos/tests/test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 162, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : [3](45.8241,40.0216,3.90729) != 45.820688332486334, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 744 DISPLACEMENT results.

----------------------------------------------------------------------
~~~
GCC 5.4

**Comment by loumalouomega** [comment]
I will check, can you try with one thread?

**Comment by loumalouomega** [comment]
Besides:

https://github.com/KratosMultiphysics/Kratos/pull/3436

**Comment by philbucher** [comment]
Still does not work, neither with 1 thread nor in #3436 

For one of the values even the data-type is wrong, how can this work in your machine?

**Comment by loumalouomega** [comment]
I have the theory that the json_check_process has some errors

**Comment by loumalouomega** [comment]
@philbucher I run 20 times with one thread and it didn't fail. I run it with 4 threads and fails some times, and as you say looks like the problem is the comparison of different types

**Comment by loumalouomega** [comment]
No, the problem of the type is the json process to compare, fix in #3478

Still looking for the error (happens 1/12 times with 8 threads)

**Comment by philbucher** [comment]
Now fails also in Travis:
~~~
    TestSimpleMortarMapper3 Failed with message: 
        Error: Check failed because std::abs(p_node_3->FastGetSolutionStepValue(TEMPERATURE) - (std::pow(p_node_3->Z(), 2) + std::pow(p_node_3->Y(), 2))) is greater than tolerance
in kratos/tests/processes/test_mortar_mapper_process.cpp:338:virtual void Testing::TestSimpleMortarMapper3::TestFunction()
~~~

**Comment by philbucher** [comment]
for some reason the test_mortar_mapper.py is only failing in release, independent of number of threads
it works in FullDebug
~~~
Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383
Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383
FF...
======================================================================
FAIL: test_mortar_mapping_quad (__main__.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mortar_mapper.py", line 164, in test_mortar_mapping_quad
    self._mapper_tests(input_filename, 4, 4)
  File "test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 154, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 10.04886216959597 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.

======================================================================
FAIL: test_mortar_mapping_quad_tri (__main__.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mortar_mapper.py", line 168, in test_mortar_mapping_quad_tri
    self._mapper_tests(input_filename, 4, 3)
  File "test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 162, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[0]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 45.82407031096666 != 45.820688332486334, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 744 DISPLACEMENT results.

----------------------------------------------------------------------
Ran 7 tests in 5.683s

FAILED (failures=2)
~~~

In FullDebug I get a lot of warnings about non-invertible matrices

the cpp-tests work on my machine

Can you try with valgrind?

**Comment by loumalouomega** [comment]
> for some reason the test_mortar_mapper.py is only failing in release, independent of number of threads
> it works in FullDebug
> 
> ```
> Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383
> Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383
> FF...
> ======================================================================
> FAIL: test_mortar_mapping_quad (__main__.TestMortarMapperCore)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_mortar_mapper.py", line 164, in test_mortar_mapping_quad
>     self._mapper_tests(input_filename, 4, 4)
>   File "test_mortar_mapper.py", line 122, in _mapper_tests
>     check.ExecuteFinalizeSolutionStep()
>   File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 154, in ExecuteFinalizeSolutionStep
>     self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
> AssertionError: False is not true : 10.04886216959597 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.
> 
> ======================================================================
> FAIL: test_mortar_mapping_quad_tri (__main__.TestMortarMapperCore)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "test_mortar_mapper.py", line 168, in test_mortar_mapping_quad_tri
>     self._mapper_tests(input_filename, 4, 3)
>   File "test_mortar_mapper.py", line 122, in _mapper_tests
>     check.ExecuteFinalizeSolutionStep()
>   File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 162, in ExecuteFinalizeSolutionStep
>     self.assertTrue(isclosethis, msg=(str(value[0]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
> AssertionError: False is not true : 45.82407031096666 != 45.820688332486334, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 744 DISPLACEMENT results.
> 
> ----------------------------------------------------------------------
> Ran 7 tests in 5.683s
> 
> FAILED (failures=2)
> ```
> 
> In FullDebug I get a lot of warnings about non-invertible matrices
> 
> the cpp-tests work on my machine
> 
> Can you try with valgrind?

Very strange,. I run it 100 times in release and fulldebug. I will try with Valgring

**Comment by loumalouomega** [comment]
@roigcarlo can be this related with the compiler version?

**Comment by roigcarlo** [comment]
The difference is too large to be fault of the compiler in my opinion. If it works in fulldebug but does not in release, I would bet for something else.

**Comment by loumalouomega** [comment]
I run it in fulldebug and release 100 times, and it is clean. Running valgring right now

**Comment by loumalouomega** [comment]
Wait, I am running again 100 times in full debug and it failed once... I will check again

**Comment by loumalouomega** [comment]
Ok, I found a missing atomic, that I thought I added but apparently not

**Comment by philbucher** [comment]
Still same problems, works in FullDebug but fails in release:
~~~
======================================================================
FAIL: test_mortar_mapping_quad (__main__.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mortar_mapper.py", line 164, in test_mortar_mapping_quad
    self._mapper_tests(input_filename, 4, 4)
  File "test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 154, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 10.04886216959597 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.

======================================================================
FAIL: test_mortar_mapping_quad_tri (__main__.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mortar_mapper.py", line 168, in test_mortar_mapping_quad_tri
    self._mapper_tests(input_filename, 4, 3)
  File "test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 162, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[0]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 45.82407031096667 != 45.820688332486334, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 744 DISPLACEMENT results.

----------------------------------------------------------------------
Ran 7 tests in 6.587s
~~~

**Comment by loumalouomega** [comment]
I run it 100 times I don't understand :P

**Comment by philbucher** [comment]
are you doing sth different in release than in FullDebug?

**Comment by philbucher** [comment]
It works in the nightly build

**Comment by loumalouomega** [comment]
I am running 100 in both cases

**Comment by philbucher** [comment]
I am not sure if this is necessary, I get consistently a different result
=> plus I get thousands (really a lot!) of those warnings (only in FullDebug):
`Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383`

**Comment by loumalouomega** [comment]
I got clean both debug and release, I am running again and I will post the 100 runs

**Comment by philbucher** [comment]
hm not sure if this helps ...
What abt those warnings?

**Comment by loumalouomega** [comment]
There are warnings expected in fulldebug, this happens for very small cuts, are just informative for debugging. The failing in the coordinates you are getting make me think there is something else

**Comment by loumalouomega** [comment]
[out.txt](https://github.com/KratosMultiphysics/Kratos/files/2629227/out.txt)

**Comment by loumalouomega** [comment]
@philbucher which tests fails?, fails always?, which compiler are you using?

**Comment by philbucher** [comment]
Standard: Gcc 5.4, Ubuntu 16.04
~~~
test_less_basic_mortar_mapping_triangle (__main__.TestMortarMapperCore) ... ok
test_less_basic_mortar_mapping_triangle_pure_implicit (__main__.TestMortarMapperCore) ... ok
test_mortar_mapping_quad (__main__.TestMortarMapperCore) ... Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383
Quadrilateral3D4: detJ =	2.53952e-07 DeltaX =	[2](401.4,-512.91) stopping calculation. Iteration:	383
FAIL
test_mortar_mapping_quad_tri (__main__.TestMortarMapperCore) ... FAIL
test_mortar_mapping_tri_quad (__main__.TestMortarMapperCore) ... ok
test_mortar_mapping_triangle (__main__.TestMortarMapperCore) ... ok
test_simple_curvature_mortar_mapping_triangle (__main__.TestMortarMapperCore) ... ok

======================================================================
FAIL: test_mortar_mapping_quad (__main__.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mortar_mapper.py", line 164, in test_mortar_mapping_quad
    self._mapper_tests(input_filename, 4, 4)
  File "test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 154, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 10.04886216959597 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.

======================================================================
FAIL: test_mortar_mapping_quad_tri (__main__.TestMortarMapperCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mortar_mapper.py", line 168, in test_mortar_mapping_quad_tri
    self._mapper_tests(input_filename, 4, 3)
  File "test_mortar_mapper.py", line 122, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/from_json_check_result_process.py", line 162, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[0]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 45.82407031096667 != 45.820688332486334, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 744 DISPLACEMENT results.

----------------------------------------------------------------------
Ran 7 tests in 6.002s

FAILED (failures=2)
~~~

**Comment by loumalouomega** [comment]
Can you try something?, go to the test, comment the generator of json results, run, revert comment, run. Maybe with the precision of your machine the tolerances are failing

**Comment by philbucher** [comment]
If I create new results it works in release but fails in FullDebug :/

**Comment by loumalouomega** [comment]
But why?????

**Comment by loumalouomega** [comment]
x86 or x86-64?

**Comment by philbucher** [comment]
Thats a good question ^^
64

**Comment by loumalouomega** [comment]
If we change the tolerance one does it work?

**Comment by philbucher** [comment]
I am closing this bcs I think I am the only one having problems with this...

We can keep it in mind, maybe we come across sth
