### ISSUE TITLE
ContactStructuralMechanics tests failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3628]
The following tests are failing for me in master:
~~~
======================================================================
FAIL: test_dynamic_search_quad (test_dynamic_search.TestDynamicSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/test_dynamic_search.py", line 161, in test_dynamic_search_quad
    self._dynamic_search_tests(input_filename, 4)
  File "/home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/test_dynamic_search.py", line 131, in _dynamic_search_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.27648446766608664 != 0.28343741620962215, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 1017 NORMAL_GAP results.

======================================================================
FAIL: test_mortar_mapping_quad (test_mortar_mapper.TestMortarMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/test_mortar_mapper.py", line 210, in test_mortar_mapping_quad
    self._mapper_tests(input_filename, 4, False)
  File "/home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/test_mortar_mapper.py", line 176, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 10.04886216959597 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.

======================================================================
FAIL: test_execution (SmallTests.SimplePatchTestThreeDMeshTying)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 78, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philippb/software/Kratos_aux/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/kratos/python_scripts/analysis_stage.py", line 135, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_aux/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : -1.598237351915151e+50 != -0.04163056265274044, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 195 DISPLACEMENT_Y results.

----------------------------------------------------------------------
Ran 73 tests in 100.372s

FAILED (failures=3)
~~~

and 

~~~
.....ReadMatrixMarketMatrix(): unable to open /home/vicente/src/Kratos/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/A_testing_condensation.mm.
ReadMatrixMarketVector(): unable to open /home/vicente/src/Kratos/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/b_testing_condensation.rhs.
....F.................................................................................................................................F..................................................................................................................................................................................................
Ran 704 of 705 test cases in 0.468856s. 2 failed:
    TestMixedULMLinearSolverThreeDoFSystem Failed with message: 
        Error: Check failed because std::abs(ref_Dx[i] - Dx[i])/std::abs(ref_Dx[i]) = 0.0515649 is not near to 0.0 = 0 within the tolerance 0.05
in /home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_mixedulm_linear_solver.cpp:675:virtual void Testing::TestMixedULMLinearSolverThreeDoFSystem::TestFunction()

    TestShapeFunctionDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philippb/software/Kratos_aux/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:415:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, vector<long unsigned int>, Testing::IndexType, vector<double>, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3ul; long unsigned int TNumNodes = 4ul; Condition::Pointer = shared_ptr<Condition>; Testing::IndexType = long unsigned int]
~~~

**Comment by philbucher** [comment]
Release, Ubuntu 16.04, 64 bit, GCC 5.4, without Cotire

Found this while testing for #3375

**Comment by loumalouomega** [comment]
I will check

**Comment by loumalouomega** [comment]
In my machine is works perfectly, I cannot replicate this unfortunely right now

**Comment by loumalouomega** [comment]
@philbucher VM with Ubuntu 16.04.5, GCC 5.4, Release, clean. Using boost 1.59 (the only version of boost I truss)

**Comment by philbucher** [comment]
Now one test less fails

~~~
======================================================================
FAIL: test_dynamic_search_quad (test_dynamic_search.TestDynamicSearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/ContactStructuralMechanicsApplication/tests/test_dynamic_search.py", line 161, in test_dynamic_search_quad
    self._dynamic_search_tests(input_filename, 4)
  File "/home/philipp/software/Kratos_MasterBranch/applications/ContactStructuralMechanicsApplication/tests/test_dynamic_search.py", line 131, in _dynamic_search_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.25738913271088587 != 0.28343741620962215, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 1017 NORMAL_GAP results.

======================================================================
FAIL: test_mortar_mapping_quad (test_mortar_mapper.TestMortarMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/ContactStructuralMechanicsApplication/tests/test_mortar_mapper.py", line 210, in test_mortar_mapping_quad
    self._mapper_tests(input_filename, 4, False)
  File "/home/philipp/software/Kratos_MasterBranch/applications/ContactStructuralMechanicsApplication/tests/test_mortar_mapper.py", line 176, in _mapper_tests
    check.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 157, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 10.048862258578897 != 10.043189538154905, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 242 TEMPERATURE results.
~~~

~~~
..............................................................................................ReadMatrixMarketMatrix(): unable to open /home/vicente/src/Kratos/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/A_testing_condensation.mm.
ReadMatrixMarketVector(): unable to open /home/vicente/src/Kratos/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/b_testing_condensation.rhs.
....F.........................................................................................................F...........................F.....................................................................................................................................................................................................
Ran 745 of 746 test cases in 0.397574s. 3 failed:
    TestMixedULMLinearSolverThreeDoFSystem Failed with message: 
        Error: Check failed because std::abs(ref_Dx[i] - Dx[i])/std::abs(ref_Dx[i]) = 0.0581102 is not near to 0.0 = 0 within the tolerance 0.05
in /home/philipp/software/Kratos_MasterBranch/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_mixedulm_linear_solver.cpp:675:virtual void Testing::TestMixedULMLinearSolverThreeDoFSystem::TestFunction()

    TestSPRErrorProcess2 Failed with message: 
        Error: Check failed because (0.122409 - process_info[ERROR_OVERALL])/0.122409 is greater than 1.0e-5
in /home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp:289:virtual void Testing::TestSPRErrorProcess2::TestFunction()

    TestShapeFunctionDerivativesQuadrilateral2 Failed with message: 
        Error: YOUR INITIAL SPLITTING DOES NOT COINCIDE WITH THE CURRENT ONE

in /home/philipp/software/Kratos_MasterBranch/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/test_derivatives.cpp:415:void Testing::TestDerivatives(ModelPart&, Condition::Pointer, Condition::Pointer, Condition::Pointer, Condition::Pointer, vector<long unsigned int>, Testing::IndexType, vector<double>, Testing::IndexType, Testing::DerivateToCheck, Testing::CheckLevel) [with long unsigned int TDim = 3; long unsigned int TNumNodes = 4; Condition::Pointer = shared_ptr<Condition>; Testing::IndexType = long unsigned int]
~~~

why do you specify the absolute path? Maybe thats why it fails?

**Comment by philbucher** [comment]
BTW your app takes ages to link, how do you develop anything
takes like 15min or even more on my laptop
Thats usually the time I need to compile KratosCore and StructuralMechanics :)

**Comment by loumalouomega** [comment]
Too many templates and AD generated code

**Comment by loumalouomega** [comment]
BTW, in my machine all tests work

**Comment by philbucher** [comment]
At least those ones I am not surprised that are not working on my machine :)
~~~
ReadMatrixMarketMatrix(): unable to open /home/vicente/src/Kratos/applications/ContactStructuralMechanicsApplication/tests/cpp_tests/A_testing_condensation.mm.
~~~

Regarding the other tests I am not sure, no clue why they are not working on my machines

Will close this
