### ISSUE TITLE
Test FSIapp is failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4256]
~~~
======================================================================
FAIL: test_mvqn_recursive_accelerator_variable_stiffness (convergence_accelerator_spring_test.ConvergenceAcceleratorSpringTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/FSIapplication/tests/convergence_accelerator_spring_test.py", line 245, in test_mvqn_recursive_accelerator_variable_stiffness
    self.test_mvqn_recursive_accelerator(forceA,forceB,solution)
  File "/home/philipp/software/Kratos_prod/applications/FSIapplication/tests/convergence_accelerator_spring_test.py", line 184, in test_mvqn_recursive_accelerator
    self.test_accelerator(force1,force2,solution,mvqn_recursive_settings)
  File "/home/philipp/software/Kratos_prod/applications/FSIapplication/tests/convergence_accelerator_spring_test.py", line 173, in test_accelerator
    self.assertAlmostEqual(expected_x[i],x_guess[i],delta=self.assert_delta)
AssertionError: 0.3333333333333335 != -2.0732226561216084e+88 within 1e-07 delta

Stdout:

Testing accelerator:  MVQN_recursive
~~~

it only fails sometimes, guess it has to do with initialization

**Comment by rubenzorrilla** [comment]
:man_facepalming: Thanks for reporting. I'll have a look ASAP.

**Comment by pooyan-dadvand** [comment]
I understand that this is for the release. Isn't it?

**Comment by philbucher** [comment]
Ping
Also there is a test that does not set the paths correctly hence it fails if run from the core

**Comment by philbucher** [comment]
The mvqn test was not fixed

**Comment by rubenzorrilla** [comment]
> The mvqn test was not fixed

True, I though that `partially fixes` doesn't close the issues. I'll try to have a look to it during next week.

**Comment by rubenzorrilla** [comment]
@philbucher I tried and it works. Is still crashing in your machine?

**Comment by philbucher** [comment]
i guess we can close it, I will reopen if I see the error again
Thx for your help
