### ISSUE TITLE
The vtk io tests are failing in windows

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#4269]
I am getting the following error in windows:

```
======================================================================
ERROR: test_ascii_vtk_output (test_vtk_output_process.TestVtkOutputProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_vtk_output_process.py", line 16, in test_ascii_vtk_output
    ExecuteBasicVTKoutputProcessCheck("ascii")
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_vtk_output_process.py", line 158, in ExecuteBasicVTKoutputProcessCheck
    os.path.join("vtk_output_process_ref_files", file_format, "Main_0_"+str(step)+".vtk"))
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_vtk_output_process.py", line 106, in Check
    }""")
RuntimeError: [json.exception.parse_error.101] parse error at line 2, column 37: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '"E:\G'

======================================================================
ERROR: test_binary_vtk_output (test_vtk_output_process.TestVtkOutputProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_vtk_output_process.py", line 19, in test_binary_vtk_output
    ExecuteBasicVTKoutputProcessCheck("binary")
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_vtk_output_process.py", line 158, in ExecuteBasicVTKoutputProcessCheck
    os.path.join("vtk_output_process_ref_files", file_format, "Main_0_"+str(step)+".vtk"))
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_vtk_output_process.py", line 106, in Check
    }""")
RuntimeError: [json.exception.parse_error.101] parse error at line 2, column 37: syntax error while parsing value - invalid string: forbidden character after backslash; last read: '"E:\G'

======================================================================
FAIL: test_ModelPart_str (test_object_printing.TestObjectPrinting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\GitLab-Runner\builds\ZgfosLiz\0\poesis\Poesis\bin\Windows\Release\kratos\tests\test_object_printing.py", line 91, in test_ModelPart_str
    self.assertMultiLineEqual(str(model_part), model_part_str)
AssertionError: '-Mai[327 chars]    -Inlets- model part\n        Number of tab[1258 chars] 0\n' != '-Mai[327 chars]    -Outlet- model part\n        Number of tab[1258 chars] 0\n'
  -Main- model part
      Buffer Size : 1
      Number of tables : 1
      Number of sub model parts : 2
      Current solution step index : 0
  
      Mesh 0 :
          Number of Nodes       : 6
          Number of Properties  : 1
          Number of Elements    : 4
          Number of Conditions  : 5
          Number of Constraints : 0
  
+     -Outlet- model part
+         Number of tables : 0
+         Number of sub model parts : 0
+ 
+         Mesh 0 :
+             Number of Nodes       : 0
+             Number of Properties  : 1
+             Number of Elements    : 0
+             Number of Conditions  : 1
+             Number of Constraints : 0
      -Inlets- model part
          Number of tables : 1
          Number of sub model parts : 2
  
          Mesh 0 :
              Number of Nodes       : 3
              Number of Properties  : 0
              Number of Elements    : 1
              Number of Conditions  : 3
              Number of Constraints : 0
+         -Inlet2- model part
+             Number of tables : 0
+             Number of sub model parts : 0
+ 
+             Mesh 0 :
+                 Number of Nodes       : 0
+                 Number of Properties  : 0
+                 Number of Elements    : 0
+                 Number of Conditions  : 2
+                 Number of Constraints : 0
          -Inlet1- model part
              Number of tables : 0
              Number of sub model parts : 0
  
              Mesh 0 :
                  Number of Nodes       : 2
                  Number of Properties  : 0
                  Number of Elements    : 0
                  Number of Conditions  : 2
                  Number of Constraints : 0
-         -Inlet2- model part
-             Number of tables : 0
-             Number of sub model parts : 0
- 
-             Mesh 0 :
-                 Number of Nodes       : 0
-                 Number of Properties  : 0
-                 Number of Elements    : 0
-                 Number of Conditions  : 2
-                 Number of Constraints : 0
-     -Outlet- model part
-         Number of tables : 0
-         Number of sub model parts : 0
- 
-         Mesh 0 :
-             Number of Nodes       : 0
-             Number of Properties  : 1
-             Number of Elements    : 0
-             Number of Conditions  : 1
-             Number of Constraints : 0


----------------------------------------------------------------------
Ran 219 tests in 17.273s
```

The first errors are due to the back slashes `"\"` in the path  of `__file__` 

Is anybody had the same issue?

**Comment by loumalouomega** [comment]
But then is json library error related?

**Comment by loumalouomega** [comment]
Because if that is the case we should communicate to the responsible of the library

**Comment by pooyan-dadvand** [comment]
As far as I understood, json don't like the single back slash in string (like C) But I'm not sure if we should put double back slash `\\` or slash `/`

**Comment by loumalouomega** [comment]
@pooyan-dadvand can you try the following code in the test:

~~~py
from __future__ import print_function, absolute_import, division

import KratosMultiphysics
import KratosMultiphysics.KratosUnittest as KratosUnittest

import KratosMultiphysics.kratos_utilities as kratos_utils
import KratosMultiphysics.vtk_output_process as vtk_output_process

import os

def GetFilePath(fileName):
    return os.path.join(os.path.dirname(os.path.realpath(__file__)), fileName)

class TestVtkOutputProcess(KratosUnittest.TestCase):
    def test_ascii_vtk_output(self):
        ExecuteBasicVTKoutputProcessCheck("ascii")

    def test_binary_vtk_output(self):
        ExecuteBasicVTKoutputProcessCheck("binary")

    def tearDown(self):
        kratos_utils.DeleteDirectoryIfExisting("test_vtk_output")

def SetupModelPart(model_part):
    model_part.AddNodalSolutionStepVariable(KratosMultiphysics.DISPLACEMENT)
    model_part.AddNodalSolutionStepVariable(KratosMultiphysics.VELOCITY)
    model_part.AddNodalSolutionStepVariable(KratosMultiphysics.PRESSURE)
    #create nodes
    model_part.CreateNewNode(1, 0.00000, 1.00000, 0.00000)
    model_part.CreateNewNode(2, 0.00000, 0.50000, 0.00000)
    model_part.CreateNewNode(3, 0.50000, 1.00000, 0.00000)
    model_part.CreateNewNode(4, 0.50000, 0.50000, 0.00000)
    model_part.CreateNewNode(5, 0.00000, 0.00000, 0.00000)
    model_part.CreateNewNode(6, 1.00000, 1.00000, 0.00000)
    model_part.CreateNewNode(7, 1.00000, 0.50000, 0.00000)
    model_part.CreateNewNode(8, 0.50000, 0.00000, 0.00000)
    model_part.CreateNewNode(9, 1.00000, 0.00000, 0.00000)
    model_part.CreateNewNode(10, 1.50000, 1.00000, 0.00000)
    model_part.CreateNewNode(11, 1.50000, 0.50000, 0.00000)
    model_part.CreateNewNode(12, 1.50000, 0.00000, 0.00000)
    model_part.CreateNewNode(13, 2.00000, 1.00000, 0.00000)
    model_part.CreateNewNode(14, 2.00000, 0.50000, 0.00000)
    model_part.CreateNewNode(15, 2.00000, 0.00000, 0.00000)
    model_part.CreateNewNode(16, 1.00000, 1.00000, 0.00000)
    model_part.CreateNewNode(17, 1.00000, 0.50000, 0.00000)
    model_part.CreateNewNode(18, 1.00000, 0.00000, 0.00000)

    #create Element
    model_part.CreateNewElement("Element2D4N", 1,
                        [14, 11, 12, 15], model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 2,
                        [13, 10, 11, 14], model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 3,
                        [11, 17, 18, 12], model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 4,
                        [10, 16, 17, 11], model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 5,
                        [2, 4, 3, 1], model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 6, [5, 8, 4, 2],
                        model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 7, [4, 7, 6, 3],
                        model_part.GetProperties()[1])
    model_part.CreateNewElement("Element2D4N", 8, [8, 9, 7, 4],
                        model_part.GetProperties()[1])

    model_part.CreateNewCondition("LineCondition2D2N", 1, [1,2], model_part.GetProperties()[1])
    model_part.CreateNewCondition("LineCondition2D2N", 2, [2,5], model_part.GetProperties()[1])
    model_part.CreateNewCondition("LineCondition2D2N", 3, [13,14], model_part.GetProperties()[1])
    model_part.CreateNewCondition("LineCondition2D2N", 4, [14,15], model_part.GetProperties()[1])

    #create a submodelpart for boundary conditions
    bcs = model_part.CreateSubModelPart("FixedEdgeNodes")
    bcs.AddNodes([1, 2, 5])
    bcs.AddConditions([1,2])

    bcmn = model_part.CreateSubModelPart("MovingNodes")
    bcmn.AddNodes([13, 14, 15])
    bcmn.AddConditions([3,4])

def SetSolution(model_part):
    time = model_part.ProcessInfo[KratosMultiphysics.TIME] + 0.158
    step = model_part.ProcessInfo[KratosMultiphysics.STEP]

    for node in model_part.Nodes:
        node.SetSolutionStepValue(KratosMultiphysics.DISPLACEMENT,0,[node.X*time,node.Y,node.Z*step])
        node.SetSolutionStepValue(KratosMultiphysics.VELOCITY,0,[2*node.X,2*node.Y,2*node.Z])
        node.SetSolutionStepValue(KratosMultiphysics.PRESSURE,0,node.X*time*step)

    for i_elem, elem in enumerate(model_part.Elements):
        elem.SetValue(KratosMultiphysics.DETERMINANT, [i_elem*0.189,time,time*step])

    for i_cond, cond in enumerate(model_part.Conditions):
        cond.SetValue(KratosMultiphysics.DENSITY, i_cond*step)
        cond.SetValue(KratosMultiphysics.YOUNG_MODULUS, i_cond*time)

def SetupVtkOutputProcess(current_model, parameters):
    return vtk_output_process.Factory(parameters, current_model)

def Check(output_file,reference_file):
    import KratosMultiphysics.compare_two_files_check_process as compare_process

    ## Settings string in json format
    params = KratosMultiphysics.Parameters("""{
        "reference_file_name" : "",
        "output_file_name"    : ""
    }""")
    params["reference_file_name"].SetString(GetFilePath(reference_file))
    params["output_file_name"].SetString(output_file)
    
    cmp_process = compare_process.CompareTwoFilesCheckProcess(params)

    cmp_process.ExecuteInitialize()
    cmp_process.ExecuteBeforeSolutionLoop()
    cmp_process.ExecuteInitializeSolutionStep()
    cmp_process.ExecuteFinalizeSolutionStep()
    cmp_process.ExecuteBeforeOutputStep()
    cmp_process.ExecuteAfterOutputStep()
    cmp_process.ExecuteFinalize()

def ExecuteBasicVTKoutputProcessCheck(file_format):
    current_model = KratosMultiphysics.Model()
    model_part_name = "Main"
    model_part = current_model.CreateModelPart(model_part_name)
    SetupModelPart(model_part)

    vtk_output_parameters = KratosMultiphysics.Parameters("""{
        "Parameters" : {
            "model_part_name"                    : "",
            "file_format"                        : "",
            "output_precision"                   : 8,
            "output_frequency"                   : 2,
            "folder_name"                        : "test_vtk_output",
            "nodal_solution_step_data_variables" : ["PRESSURE","DISPLACEMENT", "VELOCITY"],
            "element_data_value_variables"       : ["DETERMINANT"],
            "condition_data_value_variables"     : ["DENSITY", "YOUNG_MODULUS"]
        }
    }""")
    vtk_output_parameters["model_part_name"].SetString(model_part_name)
    vtk_output_parameters["file_format"].SetString(file_format)

    vtk_output_process = SetupVtkOutputProcess(current_model, vtk_output_parameters)

    time = 0.0
    dt = 0.2
    step = 0
    end_time = 1.0
    vtk_output_process.ExecuteInitialize()

    while (time <= end_time):
        time = time + dt
        step = step + 1
        model_part.ProcessInfo[KratosMultiphysics.STEP] += 1
        #print("STEP :: ", step, ", TIME :: ", time)
        SetSolution(model_part)
        vtk_output_process.ExecuteInitializeSolutionStep()
        model_part.CloneTimeStep(time)
        vtk_output_process.ExecuteFinalizeSolutionStep()
        if vtk_output_process.IsOutputStep():
            vtk_output_process.PrintOutput()

            Check(os.path.join("test_vtk_output","Main_0_" + str(step)+".vtk"),\
                os.path.join("vtk_output_process_ref_files", file_format, "Main_0_"+str(step)+".vtk"))

            Check(os.path.join("test_vtk_output","Main_FixedEdgeNodes_0_" + str(step)+".vtk"),\
                os.path.join("vtk_output_process_ref_files", file_format, "Main_FixedEdgeNodes_0_"+str(step)+".vtk"))

            Check(os.path.join("test_vtk_output","Main_MovingNodes_0_"+str(step)+".vtk"),\
                os.path.join("vtk_output_process_ref_files", file_format, "Main_MovingNodes_0_"+str(step)+".vtk"))


if __name__ == '__main__':
    KratosUnittest.main()
~~~

I use the SetString instead

**Comment by pooyan-dadvand** [comment]
Works for me on local machine! Thanks!
