### ISSUE TITLE
[StructuralMechanicsApplication] Tests failing after last changes 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#4493]
~~~sh
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Fofi4PointTentCableTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vicente/src/Kratos/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/from_json_check_result_process.py", line 126, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : -0.04727223880880021 != -0.03131864022032899, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 2 DISPLACEMENT_Z results.

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.Simple3D2NTrussTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vicente/src/Kratos/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/from_json_check_result_process.py", line 126, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 0.0015960661694407463 != 0.0, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 2 REACTION_Y results.
~~~

**Comment by philbucher** [comment]
is this release or master-branch?

**Comment by loumalouomega** [comment]
Máster
