### ISSUE TITLE
Problem running parallel jobs

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#4552]
Hello

I ran the CFD example in parallel

/KratosWorkshop2019_high_rise_building_CFD.gid$ mpirun -np 3 python3 MainKratos.py 

and has this error

Traceback (most recent call last):
  File "MainKratos.py", line 31, in <module>
    simulation = FluidDynamicsAnalysisWithFlush(model,parameters)
  File "MainKratos.py", line 12, in __init__
    super(FluidDynamicsAnalysisWithFlush,self).__init__(model,project_parameters)
  File "/home/hbui/kratos_bcn3/applications/FluidDynamicsApplication/python_scripts/fluid_dynamics_analysis.py", line 35, in __init__
    super(FluidDynamicsAnalysis,self).__init__(model,parameters)
  File "/home/hbui/kratos_bcn3/kratos/python_scripts/analysis_stage.py", line 41, in __init__
    self._GetSolver().AddVariables() # this creates the solver and adds the variables
  File "/home/hbui/kratos_bcn3/kratos/python_scripts/analysis_stage.py", line 198, in _GetSolver
    self._solver = self._CreateSolver()
  File "/home/hbui/kratos_bcn3/applications/FluidDynamicsApplication/python_scripts/fluid_dynamics_analysis.py", line 39, in _CreateSolver
    return python_solvers_wrapper_fluid.CreateSolver(self.model, self.project_parameters)
  File "/home/hbui/kratos_bcn3/applications/FluidDynamicsApplication/python_scripts/python_solvers_wrapper_fluid.py", line 72, in CreateSolver
    return CreateSolverByParameters(model, solver_settings, parallelism)
  File "/home/hbui/kratos_bcn3/applications/FluidDynamicsApplication/python_scripts/python_solvers_wrapper_fluid.py", line 56, in CreateSolverByParameters
    solver_module = __import__(solver_module_name)
  File "/home/hbui/kratos_bcn3/applications/FluidDynamicsApplication/python_scripts/trilinos_navier_stokes_solver_vmsmonolithic.py", line 9, in <module>
    import KratosMultiphysics.TrilinosApplication as KratosTrilinos     # MPI solvers
  File "/home/hbui/kratos_bcn3/KratosMultiphysics/TrilinosApplication/__init__.py", line 2, in <module>
    from KratosTrilinosApplication import *
ImportError: /opt/trilinos-12.10.1/lib/libamesos.so.12: undefined symbol: mpi_type_free_

Does anyone have the same problem like me?

**Comment by RiccardoRossi** [comment]
you jave some yrouble with the trilinos lob and the mpi lib you are using.
(see the last line)

**Comment by vryy** [comment]
Of course that is problem with trilinos lib. But libmpi.so surely contains the trace for mpi_type_free so not sure where this problem comes from.

**Comment by RiccardoRossi** [comment]
Hi @vryy i can only make two guesses:

1 - in the compilation of trilinos it was linked the static version of the mpi libs, which Kratos doesn't link to (deliberately, since we prefer the dynamic lib). for this reason the mpi.a is not loaded and you don't have the symbol. You might resolve this by using LD_PRELOAD to load the mpi library first
2 - If 1 is not the problem, than you might have a mismatch between the mpi library used in linking the trilinos direct solvers (amesos) and the one used in kratos. note that if you are manually compiling amesos and including for example superlu your problem may come out of the compilation of the TPL

**Comment by vryy** [comment]
1/ LD_PRELOAD is a good point although it doesn't help in this case
2/ I make sure the mpi used to compile Kratos is the same as Trilinos

In fact the problem is that I used quite a new mpi to compile the auxiliary libraries. There are some deprecated symbols, see below:

https://www.open-mpi.org/software/ompi/major-changes.php

Recompile everything with openmpi-2.1.6 removed all problems.
