### ISSUE TITLE
[StructuralMechnics] AdjointBeamtest failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4608]
What I told you, this fails for me since it was initially committed
~~~
======================================================================
FAIL: test_nodal_reaction_response (test_adjoint_sensitivity_analysis_beam_3d2n_structure.TestAdjointSensitivityAnalysisBeamStructure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_adjoint_sensitivity_analysis_beam_3d2n_structure.py", line 145, in test_nodal_reaction_response
    adjoint_analysis.Run()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 180, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[gp]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking elem " + str(elem.Id) + " " + variable_name + " results."))
AssertionError: False is not true : -1.2500070027281254 != -1.249994220896042, rel_tol = 1e-06, abs_tol = 1e-05 : Error checking elem 10 I22_SENSITIVITY results.
~~~

**Comment by MFusseder** [comment]
I will have a deeper look on it. This is a bit strange since the test works on my machine and also on the computer of some colleagues I ask to run it.

**Comment by armingeiser** [comment]
And in the nightly build it runs as well.
