### ISSUE TITLE
[StructuralMechaincs] RVE test fails

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4653]
fails on my laptop, Gcc7.3, python 3.6, without cotire, independent of number of threads, fails every time
~~~
======================================================================
ERROR: test_rve_computation_block_version (test_rve_analytic.TestRVESimplestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_rve_analytic.py", line 22, in test_rve_computation_block_version
    self._aux_rve_computation(parameters)
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/test_rve_analytic.py", line 72, in _aux_rve_computation
    simulation.Run()
  File "/home/philipp/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/python_scripts/rve_analysis.py", line 81, in RunSolutionLoop
    stress_and_strain.append(self._ComputeEquivalentStress(0, 0, perturbation, boundary_mp, averaging_mp))
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/python_scripts/rve_analysis.py", line 273, in _ComputeEquivalentStress
    self.__CustomInitializeSolutionStep(strain, boundary_mp, averaging_mp)
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/python_scripts/rve_analysis.py", line 54, in __CustomInitializeSolutionStep
    self._ApplyPeriodicity(strain, averaging_mp, boundary_mp)
  File "/home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/python_scripts/rve_analysis.py", line 333, in _ApplyPeriodicity
    periodicity_utility.AssignPeriodicity(self.min_z_face, self.max_z_face, strain, KratosMultiphysics.Vector([0.0, 0.0, dz]))
RuntimeError: Error: Counterpart not found for slave node 8

in /home/philipp/software/Kratos_prod/applications/StructuralMechanicsApplication/custom_utilities/rve_periodicity_utility.cpp:76:void RVEPeriodicityUtility::AssignPeriodicity(ModelPart&, ModelPart&, const Matrix&, const Vector&)
~~~

**Comment by loumalouomega** [comment]
The block version is for @RiccardoRossi, the elimination is my thing (still
only my list)

**Comment by RiccardoRossi** [comment]
i will take a look when you can.

@vicente
this message comes from.the search, not from the builder

**Comment by philbucher** [comment]
This still fails, but only on my laptop, could be some tolerance issue

**Comment by RiccardoRossi** [comment]
is this still failing?

**Comment by loumalouomega** [comment]
Yes, I haven't found the error yet. It is an OMP bug. If you run the test
with 8 threads 100 times fails approximately 12 times. I commented all the
OMP loops and still failing, so my theory is that the OMP loop which fails
is defined in the base elimination B&S. But I couldn't found it yet.

**Comment by roigcarlo** [comment]
Is this fixed?

**Comment by philbucher** [comment]
haven't had this problem again
Closing, will reopen if reappaers
