### ISSUE TITLE
Minor issues in PotentialFlow

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5449]
You are missing some `skiptest`s:
#
several for the MeshingApp (there are more tests failing)
~~~
test_WakeProcess3DSmall (potential_flow_test_factory.PotentialFlowTests) ... ERROR

======================================================================
ERROR: test_EmbeddedCircleNoWake (potential_flow_test_factory.PotentialFlowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/process_factory.py", line 37, in ConstructListOfProcesses
    python_module = import_module(full_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/python_scripts/level_set_remeshing_process.py", line 3, in <module>
    import KratosMultiphysics.MeshingApplication as MeshingApplication
ImportError: No module named 'KratosMultiphysics.MeshingApplication'
~~~

BTW do you really need the meshingapp here? the name of the test suggests otherwise 

#

For numpy stl (there are more tests failing)
~~~
======================================================================
ERROR: test_WakeProcess3DNodesOnWake (potential_flow_test_factory.PotentialFlowTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 100, in test_WakeProcess3DNodesOnWake
    self._runTest(settings_file_name)
  File "/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/tests/potential_flow_test_factory.py", line 212, in _runTest
    potential_flow_analysis.Run()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/analysis_stage.py", line 49, in Run
    self.Initialize()
  File "/home/philippb/software/Kratos_Master/kratos/python_scripts/analysis_stage.py", line 87, in Initialize
    process.ExecuteInitialize()
  File "/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/python_scripts/define_wake_process_3d.py", line 76, in ExecuteInitialize
    self.__CreateWakeModelPart()
  File "/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/python_scripts/define_wake_process_3d.py", line 120, in __CreateWakeModelPart
    from stl import mesh #this requires numpy-stl
ImportError: No module named 'stl'
~~~

#

compiler warning:
~~~
In file included from /home/philippb/software/Kratos_Master/kratos/includes/process_info.h:27:0,
                 from /home/philippb/software/Kratos_Master/kratos/includes/model_part.h:28,
                 from /home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.h:17,
                 from /home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:14:
/home/philippb/software/Kratos_Master/kratos/containers/data_value_container.h: In member function ‘void Kratos::Define2DWakeProcess::SaveTrailingEdgeNode()’:
/home/philippb/software/Kratos_Master/kratos/containers/data_value_container.h:268:28: warning: ‘trailing_edge_node’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             mData.push_back(ValueType(&rThisVariable,new TDataType(rValue))); //TODO: this shall be insert not push_back
                            ^
/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:123:15: note: ‘trailing_edge_node’ was declared here
     NodeType* trailing_edge_node;
~~~

**Comment by marcnunezc** [comment]
Hi @philbucher ,

Regarding the warning:

```
In file included from /home/philippb/software/Kratos_Master/kratos/includes/process_info.h:27:0,
                 from /home/philippb/software/Kratos_Master/kratos/includes/model_part.h:28,
                 from /home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.h:17,
                 from /home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:14:
/home/philippb/software/Kratos_Master/kratos/containers/data_value_container.h: In member function ‘void Kratos::Define2DWakeProcess::SaveTrailingEdgeNode()’:
/home/philippb/software/Kratos_Master/kratos/containers/data_value_container.h:268:28: warning: ‘trailing_edge_node’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             mData.push_back(ValueType(&rThisVariable,new TDataType(rValue))); //TODO: this shall be insert not push_back
                            ^
/home/philippb/software/Kratos_Master/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:123:15: note: ‘trailing_edge_node’ was declared here
     NodeType* trailing_edge_node;
```

Do you know why this is happening? Since this variable is being used in this function:


https://github.com/KratosMultiphysics/Kratos/blob/605119cde8c4c7a6a08db7ca71f3f81804a0474f/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp#L120-L132

**Comment by philbucher** [comment]
@marcnunezc this code would crash if `mrBodyModelPart` has no nodes, hence the warning is correct I think.
Maybe a check for no nodes would prevent this?

Do you get this warning?

**Comment by marcnunezc** [comment]
Yes I do get the warning!

Ok I see what you mean now!
