### ISSUE TITLE
[Solid] not running

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#5456]
The default cases in the interface are not running

```
Traceback (most recent call last):
  File "MainKratos.py", line 7, in <module>
    MainSolid.Solution(KratosMultiphysics.Model()).Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\MainSolid.py", line 32, in __init__
    self.ProjectParameters = self._import_project_parameters(file_parameters)
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\MainSolid.py", line 266, in _import_project_parameters
    import input_manager
ModuleNotFoundError: No module named 'input_manager'
```

Also in the application tests
```
PS E:\PROYECTOS\Kratos\applications\SolidMechanicsApplication\tests> runkratos.exe .\run_test.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-7fafdb9b31-Release
Compiled with OpenMP support.
Maximum OpenMP threads: 8.
Importing    KratosConstitutiveModelsApplication
            __  __      _           _      _
    KRATOS |  \/  |__ _| |_ ___ _ _(_)__ _| |
           | |\/| / _` |  _/ -_) '_| / _` | |
           |_|  |_\__,_|\__\___|_| |_\__,_|_| MODELS
Initialize KratosConstitutiveModelsApplication...
Importing    KratosSolidMechanicsApplication
            ___      _ _    _
    KRATOS / __| ___| (_)__| |
           \__ \/ _ \ | / _` |
           |___/\___/_|_\__,_| MECHANICS
Initialize KratosSolidMechanicsApplication...
Traceback (most recent call last):
  File ".\run_test.py", line 16, in <module>
    import SmallTests
  File "E:\PROYECTOS\Kratos\applications\SolidMechanicsApplication\tests\SmallTests.py", line 4, in <module>
    import TestFactory as TF
  File "E:\PROYECTOS\Kratos\applications\SolidMechanicsApplication\tests\TestFactory.py", line 8, in <module>
    import MainSolid
ModuleNotFoundError: No module named 'MainSolid'
KRATOS TERMINATED WITH ERROR
PS E:\PROYECTOS\Kratos\applications\SolidMechanicsApplication\tests>
```

**Comment by jginternational** [comment]
Probably #5268

**Comment by philbucher** [comment]
closing since incactive
