### ISSUE TITLE
Missing SkipTests in tests

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6872]
I noticed when I was not compiling the ExternalSolversApp that some tests are failing in the MeshingApp and the PotentialFlowApp
Please take a look and add the corresponding SkipTests

**Comment by loumalouomega** [comment]
OK

**Comment by loumalouomega** [comment]
The meshing app looks like is not using any external solver, which tests are failing?

**Comment by philbucher** [comment]
~~~
2020-05-05T08:42:38.3607153Z ======================================================================
2020-05-05T08:42:38.3607639Z ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamTest)
2020-05-05T08:42:38.3608705Z ----------------------------------------------------------------------
2020-05-05T08:42:38.3609030Z Traceback (most recent call last):
2020-05-05T08:42:38.3609358Z   File "/__w/Kratos/Kratos/bin/FullDebug/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 51, in setUp
2020-05-05T08:42:38.3609671Z     self.test.Initialize()
2020-05-05T08:42:38.3610014Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/adaptative_remeshing_structural_mechanics_analysis.py", line 48, in Initialize
2020-05-05T08:42:38.3610349Z     super(AdaptativeRemeshingStructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3610691Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_analysis.py", line 53, in Initialize
2020-05-05T08:42:38.3611016Z     super(StructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3611337Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
2020-05-05T08:42:38.3611657Z     self._GetSolver().Initialize()
2020-05-05T08:42:38.3612080Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 209, in Initialize
2020-05-05T08:42:38.3612419Z     mechanical_solution_strategy = self.get_mechanical_solution_strategy()
2020-05-05T08:42:38.3612983Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 317, in get_mechanical_solution_strategy
2020-05-05T08:42:38.3613317Z     self._mechanical_solution_strategy = self._create_mechanical_solution_strategy()
2020-05-05T08:42:38.3613666Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 457, in _create_mechanical_solution_strategy
2020-05-05T08:42:38.3614072Z     mechanical_solution_strategy = self._create_linear_strategy()
2020-05-05T08:42:38.3614420Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 472, in _create_linear_strategy
2020-05-05T08:42:38.3614745Z     linear_solver = self.get_linear_solver()
2020-05-05T08:42:38.3615067Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 300, in get_linear_solver
2020-05-05T08:42:38.3615390Z     self._linear_solver = self._create_linear_solver()
2020-05-05T08:42:38.3615716Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 432, in _create_linear_solver
2020-05-05T08:42:38.3616038Z     return linear_solver_factory.ConstructSolver(linear_solver_configuration)
2020-05-05T08:42:38.3616374Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/python_linear_solver_factory.py", line 26, in ConstructSolver
2020-05-05T08:42:38.3616707Z     import_module("KratosMultiphysics." + app_name)
2020-05-05T08:42:38.3617222Z   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-05-05T08:42:38.3617550Z     return _bootstrap._gcd_import(name[level:], package, level)
2020-05-05T08:42:38.3617892Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-05-05T08:42:38.3618208Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-05-05T08:42:38.3618537Z   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-05-05T08:42:38.3619164Z ModuleNotFoundError: No module named 'KratosMultiphysics.ExternalSolversApplication'
2020-05-05T08:42:38.3619438Z 
2020-05-05T08:42:38.3619743Z ======================================================================
2020-05-05T08:42:38.3620077Z ERROR: test_execution (meshing_application_test_factory.TwoDDynamicBeamLineLoadTest)
2020-05-05T08:42:38.3620618Z ----------------------------------------------------------------------
2020-05-05T08:42:38.3620961Z Traceback (most recent call last):
2020-05-05T08:42:38.3621305Z   File "/__w/Kratos/Kratos/bin/FullDebug/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 51, in setUp
2020-05-05T08:42:38.3621634Z     self.test.Initialize()
2020-05-05T08:42:38.3621984Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/adaptative_remeshing_structural_mechanics_analysis.py", line 48, in Initialize
2020-05-05T08:42:38.3622355Z     super(AdaptativeRemeshingStructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3622712Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_analysis.py", line 53, in Initialize
2020-05-05T08:42:38.3623060Z     super(StructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3623399Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
2020-05-05T08:42:38.3623732Z     self._GetSolver().Initialize()
2020-05-05T08:42:38.3624138Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 209, in Initialize
2020-05-05T08:42:38.3624489Z     mechanical_solution_strategy = self.get_mechanical_solution_strategy()
2020-05-05T08:42:38.3624846Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 317, in get_mechanical_solution_strategy
2020-05-05T08:42:38.3625300Z     self._mechanical_solution_strategy = self._create_mechanical_solution_strategy()
2020-05-05T08:42:38.3625665Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 457, in _create_mechanical_solution_strategy
2020-05-05T08:42:38.3626025Z     mechanical_solution_strategy = self._create_linear_strategy()
2020-05-05T08:42:38.3626447Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 472, in _create_linear_strategy
2020-05-05T08:42:38.3626816Z     linear_solver = self.get_linear_solver()
2020-05-05T08:42:38.3627156Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 300, in get_linear_solver
2020-05-05T08:42:38.3627494Z     self._linear_solver = self._create_linear_solver()
2020-05-05T08:42:38.3627860Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 432, in _create_linear_solver
2020-05-05T08:42:38.3628199Z     return linear_solver_factory.ConstructSolver(linear_solver_configuration)
2020-05-05T08:42:38.3628550Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/python_linear_solver_factory.py", line 26, in ConstructSolver
2020-05-05T08:42:38.3628885Z     import_module("KratosMultiphysics." + app_name)
2020-05-05T08:42:38.3629783Z   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-05-05T08:42:38.3630118Z     return _bootstrap._gcd_import(name[level:], package, level)
2020-05-05T08:42:38.3630382Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-05-05T08:42:38.3630639Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-05-05T08:42:38.3631002Z   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-05-05T08:42:38.3631675Z ModuleNotFoundError: No module named 'KratosMultiphysics.ExternalSolversApplication'
2020-05-05T08:42:38.3631888Z 
2020-05-05T08:42:38.3632111Z ======================================================================
2020-05-05T08:42:38.3632355Z ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
2020-05-05T08:42:38.3632788Z ----------------------------------------------------------------------
2020-05-05T08:42:38.3633035Z Traceback (most recent call last):
2020-05-05T08:42:38.3633295Z   File "/__w/Kratos/Kratos/bin/FullDebug/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 51, in setUp
2020-05-05T08:42:38.3633545Z     self.test.Initialize()
2020-05-05T08:42:38.3633813Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/adaptative_remeshing_structural_mechanics_analysis.py", line 48, in Initialize
2020-05-05T08:42:38.3634082Z     super(AdaptativeRemeshingStructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3634368Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_analysis.py", line 53, in Initialize
2020-05-05T08:42:38.3634636Z     super(StructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3634911Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
2020-05-05T08:42:38.3635155Z     self._GetSolver().Initialize()
2020-05-05T08:42:38.3635608Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 209, in Initialize
2020-05-05T08:42:38.3635888Z     mechanical_solution_strategy = self.get_mechanical_solution_strategy()
2020-05-05T08:42:38.3636182Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 317, in get_mechanical_solution_strategy
2020-05-05T08:42:38.3636469Z     self._mechanical_solution_strategy = self._create_mechanical_solution_strategy()
2020-05-05T08:42:38.3636871Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 457, in _create_mechanical_solution_strategy
2020-05-05T08:42:38.3637156Z     mechanical_solution_strategy = self._create_linear_strategy()
2020-05-05T08:42:38.3637462Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 472, in _create_linear_strategy
2020-05-05T08:42:38.3637743Z     linear_solver = self.get_linear_solver()
2020-05-05T08:42:38.3638082Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 300, in get_linear_solver
2020-05-05T08:42:38.3638374Z     self._linear_solver = self._create_linear_solver()
2020-05-05T08:42:38.3638718Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 432, in _create_linear_solver
2020-05-05T08:42:38.3639008Z     return linear_solver_factory.ConstructSolver(linear_solver_configuration)
2020-05-05T08:42:38.3639310Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/python_linear_solver_factory.py", line 26, in ConstructSolver
2020-05-05T08:42:38.3639584Z     import_module("KratosMultiphysics." + app_name)
2020-05-05T08:42:38.3639837Z   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-05-05T08:42:38.3640103Z     return _bootstrap._gcd_import(name[level:], package, level)
2020-05-05T08:42:38.3640365Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-05-05T08:42:38.3640621Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-05-05T08:42:38.3640882Z   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-05-05T08:42:38.3641391Z ModuleNotFoundError: No module named 'KratosMultiphysics.ExternalSolversApplication'
2020-05-05T08:42:38.3641602Z 
2020-05-05T08:42:38.3641841Z ======================================================================
2020-05-05T08:42:38.3642119Z ERROR: test_execution (meshing_application_test_factory.ThreeDDynamicBeamTest)
2020-05-05T08:42:38.3642575Z ----------------------------------------------------------------------
2020-05-05T08:42:38.3642839Z Traceback (most recent call last):
2020-05-05T08:42:38.3643117Z   File "/__w/Kratos/Kratos/bin/FullDebug/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 51, in setUp
2020-05-05T08:42:38.3643384Z     self.test.Initialize()
2020-05-05T08:42:38.3643674Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/adaptative_remeshing_structural_mechanics_analysis.py", line 48, in Initialize
2020-05-05T08:42:38.3643971Z     super(AdaptativeRemeshingStructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3644267Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_analysis.py", line 53, in Initialize
2020-05-05T08:42:38.3644557Z     super(StructuralMechanicsAnalysis, self).Initialize()
2020-05-05T08:42:38.3644830Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
2020-05-05T08:42:38.3645198Z     self._GetSolver().Initialize()
2020-05-05T08:42:38.3645661Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 209, in Initialize
2020-05-05T08:42:38.3646104Z     mechanical_solution_strategy = self.get_mechanical_solution_strategy()
2020-05-05T08:42:38.3646567Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 317, in get_mechanical_solution_strategy
2020-05-05T08:42:38.3647023Z     self._mechanical_solution_strategy = self._create_mechanical_solution_strategy()
2020-05-05T08:42:38.3647611Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 457, in _create_mechanical_solution_strategy
2020-05-05T08:42:38.3648112Z     mechanical_solution_strategy = self._create_linear_strategy()
2020-05-05T08:42:38.3648532Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 472, in _create_linear_strategy
2020-05-05T08:42:38.3648941Z     linear_solver = self.get_linear_solver()
2020-05-05T08:42:38.3649404Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 300, in get_linear_solver
2020-05-05T08:42:38.3649821Z     self._linear_solver = self._create_linear_solver()
2020-05-05T08:42:38.3650233Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_solver.py", line 432, in _create_linear_solver
2020-05-05T08:42:38.3650636Z     return linear_solver_factory.ConstructSolver(linear_solver_configuration)
2020-05-05T08:42:38.3651053Z   File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/python_linear_solver_factory.py", line 26, in ConstructSolver
2020-05-05T08:42:38.3651453Z     import_module("KratosMultiphysics." + app_name)
2020-05-05T08:42:38.3651835Z   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2020-05-05T08:42:38.3652390Z     return _bootstrap._gcd_import(name[level:], package, level)
2020-05-05T08:42:38.3652786Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-05-05T08:42:38.3653179Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-05-05T08:42:38.3653570Z   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2020-05-05T08:42:38.3654197Z ModuleNotFoundError: No module named 'KratosMultiphysics.ExternalSolversApplication'
2020-05-05T08:42:38.3654552Z 
2020-05-05T08:42:38.3655102Z ----------------------------------------------------------------------
~~~

**Comment by loumalouomega** [comment]
OK, now I see
