### ISSUE TITLE
[DEM] error in win test

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7118]
I only saw this once in the Win CI, seems to happen only sometimes
~~~
 ............E..
======================================================================
ERROR: test_DEM2D_restitution_1 (test_DEM_2D_restitution.TestDEM2DRestitution)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\a\Kratos\Kratos\bin\Custom\applications\DEMApplication\tests\test_DEM_2D_restitution.py", line 162, in test_DEM2D_restitution_1
    CreateAndRunStageInOneOpenMPThread(DEM2D_RestitutionTestSolution, model, parameters_file_name)
  File "d:\a\Kratos\Kratos\bin\Custom\applications\DEMApplication\tests\test_DEM_2D_restitution.py", line 25, in CreateAndRunStageInOneOpenMPThread
    my_obj(model, project_parameters).Run()
  File "d:\a\Kratos\Kratos\bin\Custom\KratosMultiphysics\analysis_stage.py", line 51, in Run
    self.Finalize()
  File "d:\a\Kratos\Kratos\bin\Custom\applications\DEMApplication\tests\test_DEM_2D_restitution.py", line 60, in Finalize
    self.CheckRestitution(self.coeff, restitution_coefficient, tolerance)
  File "d:\a\Kratos\Kratos\bin\Custom\applications\DEMApplication\tests\test_DEM_2D_restitution.py", line 47, in CheckRestitution
    raise ValueError('Incorrect value for COEFFICIENT_OF_RESTITUTION: expected value was '+ str(reference) + ' but received ' + str(restitution_coefficient))
ValueError: Incorrect value for COEFFICIENT_OF_RESTITUTION: expected value was 1.0985200123566359 but received -1.0
~~~

@KratosMultiphysics/dem

**Comment by maceligueta** [comment]
I have been trying to reproduce this error many times in my computer but I can't. I've tried with different number of processors also, as I don't know where the ramdomness can come from...

**Comment by philbucher** [comment]
Ok maybe it was sth else, I only saw it once

We can reopen if necessary 

Thx for checking

**Comment by maceligueta** [comment]
Hi @philbucher , I managed to reproduce this error in Linux today. I will dedicate some time to it.
