### ISSUE TITLE
DAM using deprecated variables

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#7481]
**Description**
When using DAM application example in 2D in the GiD problemtype, an error appears saying that:
```
Traceback (most recent call last):
  File "MainKratos.py", line 423, in <module>
    solution.Run()
  File "MainKratos.py", line 195, in Run
    self.Initialize()
  File "MainKratos.py", line 293, in Initialize
    output_settings)
  File "E:\KratosDeploy\KratosMultiphysics\DamApplication\gid_dam_output_process.py", line 83, in __init__
    self.TranslateLegacyVariablesAccordingToCurrentStandard(param)
  File "E:\KratosDeploy\KratosMultiphysics\DamApplication\gid_dam_output_process.py", line 126, in TranslateLegacyVariablesAccordingToCurrentStandard
    if DeprecationManager.HasDeprecatedVariable(context_string, sub_settings_where_var_is, old_name, new_name):
NameError: name 'context_string' is not defined
```

**Scope**
- DAMApplication

**Environment**
- OS: Windows 10
- Branch: master
- Python 3.7

@KratosMultiphysics/dam

**Comment by joaquinirazabal** [comment]
Thank you for pointing this out @jginternational. #7471 should solve this problem.

**Comment by rubenzorrilla** [comment]
Closing as it seems to be already solved.
