### ISSUE TITLE
[Fluid] Error in tests because of time_based_ascii_file_writer_utility

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#7833]
**Description**
`FluidDynamicsApplication` tests are failing because of the `time_based_ascii_file_writer_utility.py`. I guess it is related to #7805 .

The error says `invalid file: PosixPath("xxxxxxxxxx")`

**Scope**
- `FluidDynamicsApplication` tests

**To Reproduce**
Run all the tests in the application and the error will pop up.

**Expected behavior**
I think it doesn't manage to open the check files.

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 16.10
- Branch: master
- Python 3.5.1

**Comment by riccardotosi** [comment]
Hi @rubenzorrilla, I tried to reproduce the behavior, but the error seems related to the convection diffusion application.
~~~~bash
======================================================================
ERROR: testEulerian (buoyancy_test.BuoyancyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kratos105b/Kratos/applications/FluidDynamicsApplication/tests/buoyancy_test.py", line 36, in testEulerian
    self.testBuoyancy()
  File "/home/kratos105b/Kratos/applications/FluidDynamicsApplication/tests/buoyancy_test.py", line 63, in testBuoyancy
    self.setUpSolvers()
  File "/home/kratos105b/Kratos/applications/FluidDynamicsApplication/tests/buoyancy_test.py", line 107, in setUpSolvers
    thermal_solver.AddVariables(self.fluid_model_part)
AttributeError: module 'KratosMultiphysics.ConvectionDiffusionApplication.convection_diffusion_solver' has no attribute 'AddVariables'

Stdout:
-FluidModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 0
    Current solution step index : 0
    DOMAIN_SIZE : 2

    Number of Geometries  : 0
    Mesh 0 :
        Number of Nodes       : 0
        Number of Properties  : 0
        Number of Elements    : 0
        Number of Conditions  : 0
        Number of Constraints : 0






======================================================================
ERROR: testThermalExpansionCoefficient (buoyancy_test.BuoyancyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kratos105b/Kratos/applications/FluidDynamicsApplication/tests/buoyancy_test.py", line 43, in testThermalExpansionCoefficient
    self.testBuoyancy()
  File "/home/kratos105b/Kratos/applications/FluidDynamicsApplication/tests/buoyancy_test.py", line 63, in testBuoyancy
    self.setUpSolvers()
  File "/home/kratos105b/Kratos/applications/FluidDynamicsApplication/tests/buoyancy_test.py", line 107, in setUpSolvers
    thermal_solver.AddVariables(self.fluid_model_part)
AttributeError: module 'KratosMultiphysics.ConvectionDiffusionApplication.convection_diffusion_solver' has no attribute 'AddVariables'

Stdout:
-FluidModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 0
    Current solution step index : 0
    DOMAIN_SIZE : 2

    Number of Geometries  : 0
    Mesh 0 :
        Number of Nodes       : 0
        Number of Properties  : 0
        Number of Elements    : 0
        Number of Conditions  : 0
        Number of Constraints : 0
~~~~

**Comment by rubenzorrilla** [comment]
I'm completely sure. You are not running all the tests.

**Comment by riccardotosi** [comment]
Can you refer to which test is failing? Probably I am not compiling some applications.

**Comment by rubenzorrilla** [comment]
- `fluid_analysis_test.FluidAnalysisTest`
- `adjoint_fluid_test.AdjointFluidTest`
- `adjoint_vms_sensitivity_2d.AdjointVMSSensitivity2D`
- `test_flows_measuring_utility.FlowsMeasuringUtilityTest`
