### ISSUE TITLE
[Core] Missing test for cut plane utility

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#7919]
**Description**
I've tested the creation of plane_output using:

```
        "plane_output" : [{
                            "point"  : [42.86,0.0,0.0],
                            "normal" : [1.0,0.0,0.0]
                        },{
                            "point"  : [0.0,0.0,0.0],
                            "normal" : [0.0,1.0,0.0]
                        }]
```

**To Reproduce**
I'm using the release 8.1
I attach an example to test it
[fail_fluid_3d_cuts.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/5631425/fail_fluid_3d_cuts.gid.zip)

**Expected behavior**
It should create the cut planes for the output

**Current behavior**
This is the output I get:
```
::[PythonSolver]:: : Finished reading model part.
Read materials: Started
Read materials: Finished
TetrahedralMeshOrientationCheck: No inverted elements found
Mesh orientation check found 10960 inverted conditions.
NavierStokesSolverMonolithic: Model reading finished.
NavierStokesSolverMonolithic: Fluid solver DOFs added correctly.
[WARNING] VtkOutput: Modelpart "fluid_computational_model_part" has both elements and conditions.
Giving precedence to elements and writing only elements!
smallest_edge : 0.513874
"Generating Cutting plane with the following data:" : Generating Cutting plane with the following data:
versor : [3](1,0,0)
Xp : [3](-214.29,0,0)
Check failed in file C:\CompiledLibs\boost_1_67_0\boost/numeric/ublas/matrix_sparse.hpp at line 2983:
!preserve
Traceback (most recent call last):
  File ".\MainKratos.py", line 32, in <module>
    simulation.Run()
  File "C:\Users\garat\Desktop\kratos_rilis\KratosMultiphysics\analysis_stage.py", line 49, in Run
    self.Initialize()
  File "C:\Users\garat\Desktop\kratos_rilis\KratosMultiphysics\analysis_stage.py", line 93, in Initialize
    process.ExecuteInitialize()
  File "C:\Users\garat\Desktop\kratos_rilis\KratosMultiphysics\gid_output_process.py", line 172, in ExecuteInitialize
    self._initialize_cut_output(plane_output_configuration)
  File "C:\Users\garat\Desktop\kratos_rilis\KratosMultiphysics\gid_output_process.py", line 397, in _initialize_cut_output
    self.__define_output_plane(cut_data)
  File "C:\Users\garat\Desktop\kratos_rilis\KratosMultiphysics\gid_output_process.py", line 490, in __define_output_plane
    0.01)
RuntimeError: Error: internal logic
in kratos/utilities/cutting_utility.h:182:CuttingUtility::GenerateCut

KRATOS TERMINATED WITH ERROR
```

Wich is extra freak because ` C:\CompiledLibs\boost_1_67_0` does not exist in my machine

**Extra**
I could not find any example or test

**Comment by jginternational** [comment]
Works fine with the latest release by @roigcarlo 

Anyway, we should add a test @rubenzorrilla
