### ISSUE TITLE
Error in StructuralMechanicsApplication test

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#8134]
**Description**
I got the following error in #8075 (ubuntu (FullDebug, gcc)):
~~~sh
Running StructuralMechanicsApplication tests
................................................................F..................................................................................................................
======================================================================
FAIL: test_UL_2D_quadrilateral_block (test_patch_test_large_strain.TestPatchTestLargeStrain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/FullDebug/applications/StructuralMechanicsApplication/tests/test_patch_test_large_strain.py", line 823, in test_UL_2D_quadrilateral_block
    self._UL_2D_quadrilateral(builder_type, linearize_on_old_iteration, 11 )
  File "/__w/Kratos/Kratos/bin/FullDebug/applications/StructuralMechanicsApplication/tests/test_patch_test_large_strain.py", line 818, in _UL_2D_quadrilateral
    self.assertEqual(mp.ProcessInfo[KratosMultiphysics.NL_ITERATION_NUMBER], expected_iterations)
AssertionError: 10 != 11

----------------------------------------------------------------------
Ran 179 tests in 25.756s

FAILED (failures=1)
/__w/Kratos/Kratos/bin/FullDebug/applications//StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py
Completed StructuralMechanicsApplication tests with exit code 1!
~~~

I do not know if this error is known or not. In case it is, feel free to close the issue. I assign to @KratosMultiphysics/structural-mechanics.

**Scope**
Where in Kratos is this bug happening. 
E.g.
- Continuous Integration

**To Reproduce**
Opening a PR should be enough.

**Expected behavior**
The test should run correctly.

**Environment**
CI: ubuntu (FullDebug, gcc)

**Comment by riccardotosi** [comment]
@KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
That test is from @RiccardoRossi

**Comment by riccardotosi** [comment]
I got this error only once (for now) in one PR. If @KratosMultiphysics/structural-mechanics or @RiccardoRossi think is not an issue, feel free to close the issue.

**Comment by rubenzorrilla** [comment]
I think this is no longer an issue (otherwise our CI would crash from time to time).
