### ISSUE TITLE
[FluidDynamics] Tests failing in nightly CLANG build

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#8526]
from last night, I think this didn't happen before
Was anything critical merged yesterday?
@KratosMultiphysics/fluid-dynamics 
~~~
Running FluidDynamicsApplication tests
.......................................................F.F....
======================================================================
FAIL: testSodShockTubeExplicitASGSShockCapturing (sod_shock_tube_test.SodShockTubeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/FluidDynamicsApplication/tests/sod_shock_tube_test.py", line 20, in testSodShockTubeExplicitASGSShockCapturing
    self._RunSodShockTubeTest()
  File "/__w/Kratos/Kratos/bin/Release/applications/FluidDynamicsApplication/tests/sod_shock_tube_test.py", line 58, in _RunSodShockTubeTest
    simulation.Run()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DENSITY, results:
Node 517 0.82628329961!=0.82628328798; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 539 0.57289959015!=0.57289961452; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 542 0.54583170176!=0.54583171989; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 543 0.54320489203!=0.54320491092; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 544 0.54372063855!=0.54372065822; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 545 0.54382890609!=0.543828926; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 546 0.54392146106!=0.54392148099; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 547 0.54505133732!=0.54505135748; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 548 0.54494261793!=0.54494264036; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 549 0.53363219933!=0.53363221662; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 551 0.5181040493!=0.51810406016; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 560 0.34834632835!=0.34834631555; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 563 0.4089803455!=0.40898036284; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 572 0.36647428183!=0.36647430215; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 573 0.33496221038!=0.33496219874; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 583 0.36120371878!=0.36120372899; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 517 0.21075769881!=0.21075768365; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 528 0.24587294286!=0.24587296865; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 530 0.2647076876!=0.2647077041; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 532 0.26552017358!=0.26552018872; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 533 0.26560363758!=0.26560365266; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 534 0.26564546844!=0.2656454835; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 535 0.2654485847!=0.26544859976; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 536 0.26428699527!=0.26428701065; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 537 0.2672659728!=0.26726598853; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 539 0.40287539108!=0.40287540312; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 552 0.41967812015!=0.41967814423; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 561 0.3875155791!=0.38751559236; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 562 0.40456526092!=0.40456524335; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 572 0.4260827694!=0.42608279698; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 573 0.32761634753!=0.32761633009; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 574 0.35127387709!=0.35127386157; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 577 0.34473855397!=0.34473854378; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 582 0.32932265487!=0.32932264482; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 585 0.2684616479!=0.26846163735; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 594 0.28497163891!=0.2849716235; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 517 1.94560822!=1.9456081845; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 518 1.9484461778!=1.9484461613; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 519 1.9584530513!=1.9584530333; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 521 1.9606386815!=1.9606386637; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 522 1.9610418441!=1.9610418263; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 523 1.9611256235!=1.9611256057; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 524 1.9610758095!=1.9610757918; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 525 1.9589720005!=1.9589719834; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 526 1.9519966135!=1.9519965998; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 528 1.4739115392!=1.4739115612; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 530 1.506995364!=1.5069953845; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 532 1.5086974346!=1.5086974551; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 533 1.5092243762!=1.5092243975; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 534 1.5093813668!=1.5093813883; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 535 1.5091461291!=1.5091461507; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 536 1.5079190076!=1.5079190289; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 537 1.5124936341!=1.5124936534; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 538 1.5365224128!=1.536522429; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 539 1.243552971!=1.243553047; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 540 1.1914442773!=1.1914443501; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 541 1.5578223308!=1.5578223422; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 542 1.195384315!=1.1953843738; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 543 1.1850559707!=1.1850560336; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 544 1.1856582375!=1.185658302; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 545 1.1858438136!=1.1858438786; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 546 1.1857527977!=1.1857528629; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 547 1.1889114307!=1.1889114953; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 548 1.195840853!=1.1958409117; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 549 1.1791483958!=1.1791484488; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 550 0.90908657084!=0.90908653343; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 551 1.1037995737!=1.1037996057; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 552 0.7970788513!=0.79707880724; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 553 0.78891863691!=0.78891860469; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 554 0.79715221947!=0.79715217795; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 555 0.7928880634!=0.79288801602; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 556 0.79166514886!=0.79166509936; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 557 0.79125391569!=0.79125386557; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 558 0.79268832177!=0.79268827103; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 559 0.80391120756!=0.80391116273; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 560 0.78941153715!=0.78941151882; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 561 0.68162233147!=0.68162230642; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 562 0.98816746996!=0.98816745379; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 563 0.94231673672!=0.94231668928; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 564 0.90531334939!=0.90531330672; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 565 0.90599310027!=0.90599306355; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 566 0.9091602122!=0.90916018065; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 567 0.90968537966!=0.90968534932; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 568 0.9104361521!=0.91043612176; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 569 0.91210097424!=0.91210094362; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 570 0.90713510707!=0.90713508016; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 571 0.86408238811!=0.86408236758; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 572 0.81238485564!=0.81238479112; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 574 0.96415428772!=0.96415426125; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 575 0.94279958029!=0.94279956034; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 576 0.93762686924!=0.93762685224; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 577 0.93780218192!=0.93780216607; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 578 0.93854876465!=0.93854875084; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 579 0.93875303546!=0.93875302215; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 580 0.93758766599!=0.93758765361; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 583 0.89552914006!=0.89552909474; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 585 0.87319507933!=0.87319506797; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 594 0.86418513866!=0.86418512016; rel_tol=1e-10, abs_tol=1e-08


======================================================================
FAIL: testSodShockTubeExplicitOSSShockCapturing (sod_shock_tube_test.SodShockTubeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/FluidDynamicsApplication/tests/sod_shock_tube_test.py", line 34, in testSodShockTubeExplicitOSSShockCapturing
    self._RunSodShockTubeTest()
  File "/__w/Kratos/Kratos/bin/Release/applications/FluidDynamicsApplication/tests/sod_shock_tube_test.py", line 58, in _RunSodShockTubeTest
    simulation.Run()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DENSITY, results:
Node 517 0.82338656805!=0.82338655007; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 518 0.83529147926!=0.83529146632; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 519 0.83648243254!=0.83648242072; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 521 0.83661126285!=0.83661125018; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 522 0.8366480388!=0.83664802619; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 523 0.83659070438!=0.83659069182; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 524 0.83638846506!=0.83638845248; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 525 0.83536403986!=0.83536402753; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 526 0.83277414813!=0.83277413776; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 528 0.63950622176!=0.6395062067; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 539 0.57296612696!=0.57296615167; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 542 0.54177346274!=0.54177348324; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 543 0.5389098783!=0.53890989806; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 544 0.53809428931!=0.5380943093; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 545 0.53823554254!=0.53823556257; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 546 0.53834694406!=0.53834696404; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 547 0.5401542971!=0.54015431726; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 548 0.54281058477!=0.54281060776; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 549 0.53114735858!=0.53114737608; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 553 0.34850629407!=0.34850628099; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 560 0.34899156079!=0.3489915474; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 563 0.41245570745!=0.41245572694; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 564 0.3932408104!=0.39324082083; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable DENSITY, results:
Node 572 0.35195468243!=0.35195469807; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 517 0.20950018112!=0.20950015711; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 521 0.1858302635!=0.18583025229; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 522 0.18621246367!=0.18621245269; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 523 0.1861583885!=0.18615837755; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 524 0.18587295773!=0.18587294679; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 525 0.18465946606!=0.18465945559; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 528 0.22490911656!=0.22490914476; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 530 0.25598386028!=0.255983876; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 532 0.25326490218!=0.25326491742; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 533 0.25372895746!=0.25372897206; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 534 0.25387080343!=0.25387081819; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 535 0.25358557208!=0.25358558696; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 536 0.25268581897!=0.25268583423; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 537 0.25731503425!=0.25731504973; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 539 0.39314116004!=0.39314117534; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 550 0.45128272603!=0.45128273702; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 552 0.41515524782!=0.41515527144; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 562 0.43369572809!=0.43369571354; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 563 0.43677588504!=0.43677589864; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 564 0.41981612717!=0.41981613833; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 572 0.41589120942!=0.41589123573; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 573 0.34791101655!=0.347911003; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 574 0.36575490001!=0.36575488561; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable MOMENTUM_X, results:
Node 594 0.2846297188!=0.28462970373; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 513 2.2554039921!=2.2554040053; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 514 2.2525542585!=2.2525542703; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 517 1.9372125261!=1.9372124555; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 518 1.9695268236!=1.9695267927; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 519 1.9720113141!=1.9720112821; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 520 2.2992580197!=2.2992580305; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 521 1.9723876993!=1.9723876639; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 522 1.9725758866!=1.9725758517; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 495 2.3658572023!=2.3658572141; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 523 1.972379572!=1.9723795372; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 506 2.2146315!=2.214631519; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 524 1.9716756361!=1.9716756012; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 507 2.2439187201!=2.2439187391; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 525 1.9681996108!=1.9681995769; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 508 2.2549471536!=2.2549471672; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 526 1.9594657903!=1.9594657626; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 510 2.2562146663!=2.2562146798; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 527 1.9637769782!=1.9637769673; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 511 2.2559236468!=2.2559236605; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 530 1.4810575943!=1.4810576057; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 512 2.2558556695!=2.2558556832; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 531 2.0148218138!=2.0148218252; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 539 1.2385392728!=1.2385393728; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 540 1.157486251!=1.1574863349; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 542 1.1815533532!=1.181553426; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 543 1.1719618832!=1.1719619619; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 544 1.168632562!=1.16863264; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 545 1.1691295594!=1.1691296375; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 546 1.1693345396!=1.169334618; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 547 1.1750994004!=1.1750994787; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 548 1.1900418336!=1.190041911; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 549 1.1731334473!=1.1731335181; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 550 0.95221394929!=0.95221392405; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 551 1.0755657883!=1.0755658174; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 552 0.77777821037!=0.77777816289; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 553 0.78058409412!=0.78058405687; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 554 0.80332276682!=0.80332272805; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 555 0.79992243752!=0.79992239766; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 556 0.79822844087!=0.79822839966; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 557 0.79865267609!=0.79865263428; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 558 0.80187299104!=0.80187294702; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 559 0.81603643106!=0.81603639119; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 560 0.79579225415!=0.79579224115; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 561 0.64231543972!=0.64231541305; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 563 0.94771778976!=0.94771774264; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 564 0.90014505843!=0.90014502204; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 565 0.90902047684!=0.90902044348; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 566 0.91356355668!=0.91356352416; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 567 0.91335812461!=0.91335809274; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 568 0.91398638586!=0.91398635351; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 569 0.91592821831!=0.91592818485; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 570 0.91292851495!=0.91292848577; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 571 0.86574640188!=0.86574638057; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 572 0.76276153014!=0.76276144605; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 573 1.0210116296!=1.021011646; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 574 0.99817280889!=0.99817279266; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 575 0.96103277838!=0.96103276785; rel_tol=1e-10, abs_tol=1e-08
Error checking for variable TOTAL_ENERGY, results:
Node 583 0.88654100064!=0.88654095251; rel_tol=1e-10, abs_tol=1e-08


----------------------------------------------------------------------
Ran 62 tests in 9.795s
~~~

**Comment by rubenzorrilla** [comment]
No. There hasn't been any change that should (in principle) affect the compressible solver...

**Comment by rubenzorrilla** [comment]
Tonight it worked so it might be related to a tolerances issue.

**Comment by philbucher** [comment]
seems like it

can you reproduce it locally?

**Comment by philbucher** [comment]
last night it failed in all OSs

you mind if we move this test to the validation suite until you had time to take a look?

**Comment by philbucher** [comment]
closing, is solved

**Comment by philbucher** [comment]
now the tests fail again :)

**Comment by rubenzorrilla** [comment]
@mrhashemi as @philbucher pointed out in the PR it is most probably due to the recent changes in the acceleration limitation.
