### ISSUE TITLE
cfl_output_process

### ISSUE THREAD

**Issue by demetrafabris** [KratosMultiphysics/Kratos#8671]
**Description**
I was trying to use the _cfl_output_process.py_ script, but it's not working.

**Scope**
Where in Kratos is this bug happening: resolution

**To Reproduce**
I attached what is written in the cfl_output_process.py, what I wrote in project paramter and the error which I obtained from the terminal
![image](https://user-images.githubusercontent.com/81411661/115882429-05b33600-a44d-11eb-9986-1020ea7f975b.png)
![image](https://user-images.githubusercontent.com/81411661/115883552-30ea5500-a44e-11eb-816f-ec8bceb3f9ce.png)
![image](https://user-images.githubusercontent.com/81411661/115883586-3e9fda80-a44e-11eb-8368-748dd41a37e8.png)

**Expected behavior**
The analysis should start.

**Environment**
OS: Ubuntu 20.10
GiD: 14
Python 3.9

**Comment by riccardotosi** [comment]
Can you replace
~~~json
"kratos_module": "KratosMultiphysics",
~~~
with
~~~json
"kratos_module": "KratosMultiphysics.FluidDynamicsApplication,
~~~
in your project parameter and see if it works?

**Comment by demetrafabris** [comment]
I’ve already tried and it still doesn’t work

**Comment by riccardotosi** [comment]
> 
> I’ve already tried and it still doesn’t work
> […](#)
> Il giorno 23 apr 2021, alle ore 17:20, riccardotosi ***@***.***> ha scritto: ﻿ Can you replace "kratos_module": "KratosMultiphysics", with "kratos_module": "KratosMultiphysics.FluidDynamicsApplication, in your project parameter and see if it works? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Can you post here the full terminal output with this change?

**Comment by demetrafabris** [comment]
```
|  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-bcabc79b59-Release
Compiled with threading support.
Maximum number of threads: 4.
Importing    KratosFluidDynamicsApplication 
Initializing KratosFluidDynamicsApplication...
NavierStokesSolverMonolithic: Construction of NavierStokesSolverMonolithic finished. 
NavierStokesSolverMonolithic: Fluid solver variables added correctly. 
::[PythonSolver]::: Reading model part. 
::[PythonSolver]::: Reading model part from file: /home/kratos/Desktop/ponte prove_traverso solo soletta_parapetto.gid/ponte prove_traverso solo soletta_parapetto.mdpa 
ModelPartIO:   [Reading Nodes    : 13751 nodes read]
ModelPartIO:   [Reading Elements : 26663 elements read] [Type: Element2D3N]
ModelPartIO:   [Reading Conditions : 778 conditions read] [Type: LineCondition2D2N]
ModelPartIO:   [Total Lines Read : 83555]
::[PythonSolver]::: Finished reading model part from mdpa file. 
ModelPart: -FluidModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 7
    Current solution step index : 0
    DOMAIN_SIZE : 2

    Number of Geometries  : 0
    Mesh 0 :
        Number of Nodes       : 13751
        Number of Properties  : 1
        Number of Elements    : 26663
        Number of Conditions  : 778
        Number of Constraints : 0

    -Drag_structure- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 246
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 0
            Number of Constraints : 0
    -FluidParts_fluid- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 13751
            Number of Properties  : 0
            Number of Elements    : 26663
            Number of Conditions  : 0
            Number of Constraints : 0
    -NoSlip2D_bottom- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 315
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 314
            Number of Constraints : 0
    -NoSlip2D_structure- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 246
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 246
            Number of Constraints : 0
    -Outlet2D_outlet- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 62
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 61
            Number of Constraints : 0
    -Slip2D- model part
        Number of tables : 0
        Number of sub model parts : 1

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 158
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 157
            Number of Constraints : 0
        -Slip2D_top- model part
            Number of tables : 0
            Number of sub model parts : 0

            Number of Geometries  : 0
            Mesh 0 :
                Number of Nodes       : 158
                Number of Properties  : 0
                Number of Elements    : 0
                Number of Conditions  : 157
                Number of Constraints : 0
    -VelocityConstraints2D_inlet- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 62
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 0
            Number of Constraints : 0
 
::[PythonSolver]:: : Finished reading model part. 
Read materials: Started
Read materials: Finished
TetrahedralMeshOrientationCheck: No inverted elements found
Mesh orientation check found 350 inverted conditions.
NavierStokesSolverMonolithic: Model reading finished. 
NavierStokesSolverMonolithic: Fluid solver DOFs added correctly. 
Traceback (most recent call last):
  File "MainKratos_custom_prova.py", line 32, in <module>
    simulation.Run()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
    self.__CreateListOfProcesses() # has to be done after importing and preparing the ModelPart
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 342, in __CreateListOfProcesses
    self._list_of_processes        = self._CreateProcesses("processes", order_processes_initialization)
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/FluidDynamicsApplication/fluid_dynamics_analysis.py", line 39, in _CreateProcesses
    list_of_processes = super(FluidDynamicsAnalysis, self)._CreateProcesses(parameter_name, initialization_order)
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 317, in _CreateProcesses
    list_of_processes += factory.ConstructListOfProcesses(value) # Does this work? or should it be processes[name]
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/process_factory.py", line 34, in ConstructListOfProcesses
    python_module = import_module(full_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/FluidDynamicsApplication/cfl_output_process.py", line 14, in <module>
    raise Exception(msg)
Exception: CFLOutputProcess requires StatisticsApplication which is not found. Please install/compile it and try again.

```

![Screenshot](https://user-images.githubusercontent.com/81411661/116096022-34c5e380-a6a9-11eb-8b1c-9f17378dad0d.png)

**Comment by riccardotosi** [comment]
As you see in the last line of the terminal output, you need to compile the StatisticsApplication to use the `cfl_output_process`:
~~~bash
Exception: CFLOutputProcess requires StatisticsApplication which is not found. Please install/compile it and try again.
~~~

Can you compile the application and let us know if it works?

**Comment by rubenzorrilla** [comment]
Note the error, I think that @riccardotosi suggestion fixed the initial issue since now you're getting into the `cfl_output_process`. However, as issued by the error, this requires the `StatisticsApplication` to work. Should be fixed by adding it to your configure file an recompiling again.

**Comment by demetrafabris** [comment]
Ok, but I don’t know how to do it. Can you help me?

**Comment by rubenzorrilla** [comment]
> Ok, but I don’t know how to do it. Can you help me?
> […](#)
> Il giorno 26 apr 2021, alle ore 16:13, Rubén Zorrilla ***@***.***> ha scritto: ﻿ Note the error, I think that @riccardotosi suggestion fixed the initial issue since now you're getting into the cfl_output_process. However, as issued by the error, this requires the StatisticsApplication to work. Should be fixed by adding it to your configure file an recompiling again. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

One very first thing, did you compile Kratos or did you get the binaries with the GiD internet retrieve tool?

**Comment by demetrafabris** [comment]
I compiled Kratos

**Comment by rubenzorrilla** [comment]
Then it should be as easy as adding the line `add_app ${KRATOS_APP_DIR}/StatisticsApplication` to the application list of your configure.sh file (be aware of not adding extra characters at the end of the line as this would throw a compilation error).

Give it a try and let us know if you have any compilation issue :wink: .

**Comment by mpentek** [comment]
Confirming: with StatisticsApplication compiled and cfl_output_process being properly called from the FluidDynAppliction it works. We use it extensively.

**Comment by demetrafabris** [comment]
I did it and I obtained this error:

```
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-bcabc79b59-Release
Compiled with threading support.
Maximum number of threads: 4.
Importing    KratosFluidDynamicsApplication 
Initializing KratosFluidDynamicsApplication...
NavierStokesSolverMonolithic: Construction of NavierStokesSolverMonolithic finished. 
NavierStokesSolverMonolithic: Fluid solver variables added correctly. 
::[PythonSolver]::: Reading model part. 
::[PythonSolver]::: Reading model part from file: /home/kratos/Desktop/ponte prove_traverso solo soletta_parapetto.gid/ponte prove_traverso solo soletta_parapetto.mdpa 
ModelPartIO:   [Reading Nodes    : 13751 nodes read]
ModelPartIO:   [Reading Elements : 26663 elements read] [Type: Element2D3N]
ModelPartIO:   [Reading Conditions : 778 conditions read] [Type: LineCondition2D2N]
ModelPartIO:   [Total Lines Read : 83555]
::[PythonSolver]::: Finished reading model part from mdpa file. 
ModelPart: -FluidModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 7
    Current solution step index : 0
    DOMAIN_SIZE : 2

    Number of Geometries  : 0
    Mesh 0 :
        Number of Nodes       : 13751
        Number of Properties  : 1
        Number of Elements    : 26663
        Number of Conditions  : 778
        Number of Constraints : 0

    -Drag_structure- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 246
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 0
            Number of Constraints : 0
    -FluidParts_fluid- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 13751
            Number of Properties  : 0
            Number of Elements    : 26663
            Number of Conditions  : 0
            Number of Constraints : 0
    -NoSlip2D_bottom- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 315
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 314
            Number of Constraints : 0
    -NoSlip2D_structure- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 246
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 246
            Number of Constraints : 0
    -Outlet2D_outlet- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 62
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 61
            Number of Constraints : 0
    -Slip2D- model part
        Number of tables : 0
        Number of sub model parts : 1

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 158
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 157
            Number of Constraints : 0
        -Slip2D_top- model part
            Number of tables : 0
            Number of sub model parts : 0

            Number of Geometries  : 0
            Mesh 0 :
                Number of Nodes       : 158
                Number of Properties  : 0
                Number of Elements    : 0
                Number of Conditions  : 157
                Number of Constraints : 0
    -VelocityConstraints2D_inlet- model part
        Number of tables : 0
        Number of sub model parts : 0

        Number of Geometries  : 0
        Mesh 0 :
            Number of Nodes       : 62
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 0
            Number of Constraints : 0
 
::[PythonSolver]:: : Finished reading model part. 
Read materials: Started
Read materials: Finished
TetrahedralMeshOrientationCheck: No inverted elements found
Mesh orientation check found 350 inverted conditions.
NavierStokesSolverMonolithic: Model reading finished. 
NavierStokesSolverMonolithic: Fluid solver DOFs added correctly. 
Importing    KratosStatisticsApplication 
    Kratos  ____  _        _   _     _   _
           / ___|| |_ __ _| |_(_)___| |_(_) ___ ___
           \___ \| __/ _` | __| / __| __| |/ __/ __|
            ___) | || (_| | |_| \__ \ |_| | (__\__ \
           |____/ \__\__,_|\__|_|___/\__|_|\___|___/ Application
Initializing KratosStatisticsApplication...
Traceback (most recent call last):
  File "MainKratos_custom_prova.py", line 32, in <module>
    simulation.Run()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
    self.__CreateListOfProcesses() # has to be done after importing and preparing the ModelPart
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 342, in __CreateListOfProcesses
    self._list_of_processes        = self._CreateProcesses("processes", order_processes_initialization)
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/FluidDynamicsApplication/fluid_dynamics_analysis.py", line 39, in _CreateProcesses
    list_of_processes = super(FluidDynamicsAnalysis, self)._CreateProcesses(parameter_name, initialization_order)
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 317, in _CreateProcesses
    list_of_processes += factory.ConstructListOfProcesses(value) # Does this work? or should it be processes[name]
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/process_factory.py", line 36, in ConstructListOfProcesses
    p = python_module.Factory(item, self.Model)
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/FluidDynamicsApplication/cfl_output_process.py", line 24, in Factory
    return CFLOutputProcess(model, settings["Parameters"])
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/FluidDynamicsApplication/cfl_output_process.py", line 88, in __init__
    self.output_file = TimeBasedAsciiFileWriterUtility(self.model_part,
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/time_based_ascii_file_writer_utility.py", line 36, in __init__
    self.__ValidateAndAssignOutputFolderPath()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/time_based_ascii_file_writer_utility.py", line 133, in __ValidateAndAssignOutputFolderPath
    self.file_name = self.file_name.with_suffix(".dat")
  File "/usr/lib/python3.8/pathlib.py", line 871, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name
```
![Screenshot from 2021-04-28 23-07-15](https://user-images.githubusercontent.com/81411661/116472712-8e2f3d80-a876-11eb-870c-f2f763690144.png)

**Comment by rubenzorrilla** [comment]
It  seems to me that you didn't specify the output folder name. Could this be the case @mpentek ?

**Comment by demetrafabris** [comment]
Yes, it seems to be this the problem
Thank you.

**Comment by rubenzorrilla** [comment]
Does it work now?

**Comment by demetrafabris** [comment]
Yes, it does now. Thank you so much

**Comment by rubenzorrilla** [comment]
OK. Then I'm closing the issue. Feel free to reopen it if needed.

**Comment by philbucher** [comment]
@mpentek it would probably make sense if this also works without giving the path.
Could you take a look please when you have time?
