### ISSUE TITLE
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge

### ISSUE THREAD

**Issue by demetrafabris** [KratosMultiphysics/Kratos#8733]
**Description**
My analysis lasts 200 s with 0.01 s time steps. Since almost 136 s it starts to not converge and it stopped with the error listed below

**Scope**
Compilation

**To Reproduce**
![image](https://user-images.githubusercontent.com/81411661/117270841-e7d8ce80-ae59-11eb-90a7-b1e43f497179.png)
![image](https://user-images.githubusercontent.com/81411661/117270865-eeffdc80-ae59-11eb-8e85-5461a3fb9d87.png)
![image](https://user-images.githubusercontent.com/81411661/117270899-f6bf8100-ae59-11eb-892a-d03d4a3851aa.png)
![image](https://user-images.githubusercontent.com/81411661/117270935-ffb05280-ae59-11eb-9c77-296ee314b9db.png)

```
Fluid Dynamics Analysis: STEP:  13655 
Fluid Dynamics Analysis: TIME:  136.5500000000208 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13655
corresponding to time 136.5500000000208
 
Fluid Dynamics Analysis: STEP:  13656 
Fluid Dynamics Analysis: TIME:  136.56000000002078 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13656
corresponding to time 136.56000000002078
 
Fluid Dynamics Analysis: STEP:  13657 
Fluid Dynamics Analysis: TIME:  136.57000000002077 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13657
corresponding to time 136.57000000002077
 
Fluid Dynamics Analysis: STEP:  13658 
Fluid Dynamics Analysis: TIME:  136.58000000002076 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13658
corresponding to time 136.58000000002076
 
Fluid Dynamics Analysis: STEP:  13659 
Fluid Dynamics Analysis: TIME:  136.59000000002075 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13659
corresponding to time 136.59000000002075
 
Fluid Dynamics Analysis: STEP:  13660 
Fluid Dynamics Analysis: TIME:  136.60000000002074 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13660
corresponding to time 136.60000000002074
 
Fluid Dynamics Analysis: STEP:  13661 
Fluid Dynamics Analysis: TIME:  136.61000000002073 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13661
corresponding to time 136.61000000002073
 
Fluid Dynamics Analysis: STEP:  13662 
Fluid Dynamics Analysis: TIME:  136.62000000002072 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13662
corresponding to time 136.62000000002072
 
Fluid Dynamics Analysis: STEP:  13663 
Fluid Dynamics Analysis: TIME:  136.63000000002071 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13663
corresponding to time 136.63000000002071
 
Fluid Dynamics Analysis: STEP:  13664 
Fluid Dynamics Analysis: TIME:  136.6400000000207 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13664
corresponding to time 136.6400000000207
 
Fluid Dynamics Analysis: STEP:  13665 
Fluid Dynamics Analysis: TIME:  136.6500000000207 
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13665
corresponding to time 136.6500000000207
 
Fluid Dynamics Analysis: STEP:  13666 
Fluid Dynamics Analysis: TIME:  136.6600000000207 
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.00057943 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.465474 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.37408 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.15523 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.953023 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.739189 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.987086 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.501842 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.0900512 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.987132 > 1e-07]
[WARNING] NavierStokesSolverMonolithic: Fluid solver did not converge for step 13666
corresponding to time 136.6600000000207
 
Fluid Dynamics Analysis: STEP:  13667 
Fluid Dynamics Analysis: TIME:  136.67000000002068 
[WARNING] AMGCL Linear Solver: Non converged linear solution. [0.776778 > 1e-07]
[WARNING] AMGCL Linear Solver: Non converged linear solution. [2.4311e+06 > 1e-07]
Traceback (most recent call last):
  File "MainKratos_custom_prova.py", line 32, in <module>
    simulation.Run()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 65, in RunSolutionLoop
    is_converged = self._GetSolver().SolveSolutionStep()
  File "/home/kratos/Kratos/bin/Release/KratosMultiphysics/FluidDynamicsApplication/fluid_solver.py", line 127, in SolveSolutionStep
    is_converged = self._GetSolutionStrategy().SolveSolutionStep()
RuntimeError: Error: Zero pivot in ILU

in kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:496:void ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::InternalSystemSolveWithPhysics(ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&, ModelPart&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = LinearSolver<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >, UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType = boost::numeric::ublas::compressed_matrix<...>; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType = boost::numeric::ublas::vector<double>]
   kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:545:void ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::BuildAndSolve(typename ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::BaseType::TSchemeType::Pointer, ModelPart&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = LinearSolver<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >, UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; typename ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::BaseType::TSchemeType::Pointer = shared_ptr<Scheme<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >, UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > > >; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType = boost::numeric::ublas::compressed_matrix<...>; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType = boost::numeric::ublas::vector<double>]
```

**Expected behavior**
The analysis should arrive to 200 s without this problem

**Environment**
- OS: Ubuntu OS: Ubuntu 20.10
- GiD14
- Python 3.8.6

**Comment by rubenzorrilla** [comment]
The linear solver is not converging. Which are your Reynolds and maximum Courant numbers?

**Comment by demetrafabris** [comment]
This is thee file with my Courant's number, the maximum was around 6, before it starts to not converging

[cfl_results.txt](https://github.com/KratosMultiphysics/Kratos/files/6433358/cfl_results.txt)

**Comment by rubenzorrilla** [comment]
These are not too high. What about the Reynolds?

**Comment by demetrafabris** [comment]
If I'm not wrong, at the height of the bridge deck (approximately 30 m) I obtained Re=92659074 (the chartacteristic dimension of the bridge deck is the width l=45.86 m and the medium wind velocity is v(z=30m)=30.31 m/s)
Isn't it strange?

**Comment by rubenzorrilla** [comment]
Don't know if it's strange, but for sure is super large. As characteristic dimension, I'd use the cross-section thickness, which would yield something of the order of 5M.
How many elements do you have in the mesh? Can you attach a snapshot of the mesh close to the cross-section.

**Comment by demetrafabris** [comment]
I've got 27K elements in the mesh

Without the mesh 
![image](https://user-images.githubusercontent.com/81411661/117305590-35b3fd80-ae7f-11eb-9534-553f38bf1310.png)


With the mesh
![image](https://user-images.githubusercontent.com/81411661/117305662-43698300-ae7f-11eb-8f31-90ff929608d9.png)

Here there is the structure
![image](https://user-images.githubusercontent.com/81411661/117305828-6b58e680-ae7f-11eb-9f2a-64c4fbf8dcb4.png)

**Comment by rubenzorrilla** [comment]
First of all, I think that this mesh is super coarse for such a high Re number. Secondly, as this is super turbulent, might it be the case that you have some vortexes that travel through the domain and arrive to the outlet?

**Comment by demetrafabris** [comment]
Yes, it is
![image](https://user-images.githubusercontent.com/81411661/117313976-a6124d00-ae86-11eb-8f21-75c4e92ac41c.png)

**Comment by rubenzorrilla** [comment]
> Yes, it is
> ![image](https://user-images.githubusercontent.com/81411661/117313976-a6124d00-ae86-11eb-8f21-75c4e92ac41c.png)

When the simulation starts to converge badly, is there inflow through the outlet?

**Comment by demetrafabris** [comment]
Actually it seems to have some problems at the inlet.
The simulation starts to converge badly around 135 s (the simulation should last 200 s).
I show you some pictures at different time steps.

100 s
![image](https://user-images.githubusercontent.com/81411661/117317649-fd65ec80-ae89-11eb-9258-e108294205be.png)

110 s
![image](https://user-images.githubusercontent.com/81411661/117317721-0f478f80-ae8a-11eb-9630-a8a4836882e0.png)

120 s
![image](https://user-images.githubusercontent.com/81411661/117317836-29816d80-ae8a-11eb-97e3-2b2297f13c0d.png)

130 s
![image](https://user-images.githubusercontent.com/81411661/117317933-41f18800-ae8a-11eb-8f63-e4154c0989b1.png)

136.65 s (When the analysis stopped)
![image](https://user-images.githubusercontent.com/81411661/117318116-6b121880-ae8a-11eb-9cba-41cb034e10a1.png)

**Comment by rubenzorrilla** [comment]
:confused: this is strange... The values in the inlet must be fixed during the entire simulation. Is there any chance that the time intervals of your inlet function are not set in accordance to the total simulation time?

**Comment by demetrafabris** [comment]
Maybe I found out the problem
I modified the end time of the analysis from 100 s to 200 s in the project parameter, but I forgot to modify the end time in the ramp-up too (I divided in ramp-up time from 0.0 s to 10.0 s and in the flow time from 10.0 s to 100.05 s). Maybe it was there the problem. Cuold it be?

**Comment by rubenzorrilla** [comment]
Closing as it seems to be solved. @demetrafabris feel free to reopen again if required.
