### ISSUE TITLE
[Contact] nightly build is failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#8879]
Since 6 days the nightly build in the Contact is failing, unfortunately only with GCC!

@loumalouomega do these test use the elimination B&S?
=> #8853 (FYI @ashishdarekar) was merged on that day, maybe sth went wrong? I reviewed it myself and it seemed fine to me.

~~~
Running ContactStructuralMechanicsApplication tests
.............F.........F...FF..F....................................................
======================================================================
FAIL: test_execution (SmallTests.PenaltyFrictionlessHyperSimplePatchFrictionalTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 3 1.040834e-17!=0.005534698; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 4 8.673617e-18!=-0.005534698; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 5 -4.015288e-05!=-0.005574027; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 6 4.015288e-05!=0.005574027; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -1.387779e-17!=-0.01941737; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.03985925!=-0.02046151; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 6.938894e-18!=-0.01941737; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.03985925!=-0.02046151; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (SmallTests.ALMPerfectStickHyperSimplePatchFrictionalTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 3 3.885781e-16!=0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 5 -0.0002007644!=-0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 4 6.661338e-16!=-0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 6 0.0002007644!=0.01422514; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -2.775558e-16!=-0.109236; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.1992963!=-0.110236; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 2.498002e-16!=-0.109236; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.1992963!=-0.110236; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (SmallTests.PenaltyNoFrictionHyperSimplePatchFrictionalTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 3 0.01210697!=0.005540362; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 5 -0.01015662!=-0.00557969; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 4 0.0007751472!=-0.005540362; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 6 0.001253829!=0.00557969; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -0.02638685!=-0.01943724; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.01549879!=-0.02044166; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 -0.01336857!=-0.01943724; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.02450449!=-0.02044166; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (SmallTests.PenaltyPerfectStickHyperSimplePatchFrictionalTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 6 0.007265317!=0.00517577; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 3 0.02019854!=1.651197e-15; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 4 0.01823679!=1.674102e-15; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.009750023!=-0.02185751; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -0.0545731!=-0.02085332; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.01662686!=-0.02185751; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 -0.008786505!=-0.02085332; rel_tol=1e-06, abs_tol=0.001


======================================================================
FAIL: test_execution (SmallTests.PenaltyHyperSimplePatchFrictionalStickTestContact)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/applications/ContactStructuralMechanicsApplication/tests/contact_structural_mechanics_test_factory.py", line 76, in test_execution
    self.test.RunSolutionLoop()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/__w/Kratos/Kratos/bin/Release/KratosMultiphysics/from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 5 -0.004935556!=-0.001500374; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_X, results:
Node 6 0.006248999!=0.002052505; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 5 -0.02372439!=-0.037413; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 6 -0.02506053!=-0.0400616; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 3 -0.02365966!=-0.006956304; rel_tol=1e-06, abs_tol=0.001
Error checking for variable DISPLACEMENT_Y, results:
Node 4 -0.02236035!=-0.00695614; rel_tol=1e-06, abs_tol=0.001


----------------------------------------------------------------------
~~~

**Comment by loumalouomega** [comment]
Uff, I need to check (we may should design a system to check nightly, but only before merge)

**Comment by philbucher** [comment]
technically I don't think it is possible to run checks and then automatically merge
we could trigger nightly builds after each merge, but I am afraid this will end up blocking the CI (one run takes ~3hrs and we can do 5 in parallel overall only)

**Comment by philbucher** [comment]
also #8548 was merged on the same day, which caused problems with the contact
@vdivine did you run the nightly tests before merging?

**Comment by loumalouomega** [comment]
> also #8548 was merged on the same day, which caused problems with the contact
> @vdivine did you run the nightly tests before merging?

In fact that should be better, as I checked the Contact in pourpose

**Comment by philbucher** [comment]
so are those test using the ElimB&S?

**Comment by loumalouomega** [comment]
> so are those test using the ElimB&S?

I cannot check right now...

**Comment by loumalouomega** [comment]
But most of my tests do not use elimination

**Comment by loumalouomega** [comment]
Looks like is OMP failure...

**Comment by philbucher** [comment]
> 
> 
> BTW: https://github.community/t/how-to-trigger-github-ci-after-merge-request-get-merged/116524/2

thats what I wrote above

**Comment by vdivine** [comment]
> 
> 
> also #8548 was merged on the same day, which caused problems with the contact
> @vdivine did you run the nightly tests before merging?

No i have not, i was not aware of nightly tests actually...

**Comment by philbucher** [comment]
I found the source: #8684 (@tteschemacher)

I have no idea how or why though

for reference the commits in this period (top ones are merged later, `xxx` means tests pass, `XXX` means tests fail)
~~~
XXX efb3ea461e6119ca1427a6b3ba98a1711e98fd2b Philipp .. 7 days ago      Merge pull request #8853 from KratosMultiphysics/core/porting_omp_to_parallel_utilities_15
    88f57b7a2fbe135cc6599b7fd001fe907b8c5c83 Vicente .. 7 days ago      Merge pull request #8844 from KratosMultiphysics/core/delete-variable-component-deprecated
XXX 879d2621fca4b186c9f4e8d462ac88f3b1d9bb06 tteschem.. 7 days ago      Merge pull request #8684 from KratosMultiphysics/core/geometry_remove_virtual
xxx 1beb715b93fab59f740f89d32305765a2beb8054 Vicente .. 7 days ago      Merge pull request #8761 from KratosMultiphysics/core/expose-erase-python
xxx 470145298ff34d78968da9ffd17d42ca48f07a75 Philipp .. 7 days ago      Merge pull request #8394 from KratosMultiphysics/core/global-lock
    c5ab014dd54c9a5edcd58b2536ee789de5775f4b riccardo.. 7 days ago      Merge pull request #8857 from KratosMultiphysics/MLMC/update-xmc
    8d7ed7f89f311c3053bddfec456b851b8f687e6e vdivine    7 days ago      Merge pull request #8548 from KratosMultiphysics/core/add-swap-pointer-vector-set
    d43fe782185571d55c5f7ea89dbbffc48d814ba7 Vicente .. 7 days ago      Merge pull request #8767 from KratosMultiphysics/core/missing-has-methods
xxx ce23f6d594e28a378c92e04bd7bd0c350dbce859 riccardo.. 7 days ago      Merge pull request #8856 from KratosMultiphysics/MLMC/update-xmc
~~~

**Comment by loumalouomega** [comment]
> I found the source: #8684 (@tteschemacher)
> 
> I have no idea how or why though
> 
> for reference the commits in this period (top ones are merged later, `xxx` means tests pass, `XXX` means tests fail)
> 
> ```
> XXX efb3ea461e6119ca1427a6b3ba98a1711e98fd2b Philipp .. 7 days ago      Merge pull request #8853 from KratosMultiphysics/core/porting_omp_to_parallel_utilities_15
>     88f57b7a2fbe135cc6599b7fd001fe907b8c5c83 Vicente .. 7 days ago      Merge pull request #8844 from KratosMultiphysics/core/delete-variable-component-deprecated
> XXX 879d2621fca4b186c9f4e8d462ac88f3b1d9bb06 tteschem.. 7 days ago      Merge pull request #8684 from KratosMultiphysics/core/geometry_remove_virtual
> xxx 1beb715b93fab59f740f89d32305765a2beb8054 Vicente .. 7 days ago      Merge pull request #8761 from KratosMultiphysics/core/expose-erase-python
> xxx 470145298ff34d78968da9ffd17d42ca48f07a75 Philipp .. 7 days ago      Merge pull request #8394 from KratosMultiphysics/core/global-lock
>     c5ab014dd54c9a5edcd58b2536ee789de5775f4b riccardo.. 7 days ago      Merge pull request #8857 from KratosMultiphysics/MLMC/update-xmc
>     8d7ed7f89f311c3053bddfec456b851b8f687e6e vdivine    7 days ago      Merge pull request #8548 from KratosMultiphysics/core/add-swap-pointer-vector-set
>     d43fe782185571d55c5f7ea89dbbffc48d814ba7 Vicente .. 7 days ago      Merge pull request #8767 from KratosMultiphysics/core/missing-has-methods
> xxx ce23f6d594e28a378c92e04bd7bd0c350dbce859 riccardo.. 7 days ago      Merge pull request #8856 from KratosMultiphysics/MLMC/update-xmc
> ```

Quite strange!

**Comment by tteschemacher** [comment]
Are you sure about that @philbucher . If you want we can revert it to see if it really changes something. However, it shouldn't change anything, unless there is a heap error somewhere else.

**Comment by loumalouomega** [comment]
> Are you sure about that @philbucher . If you want we can revert it to see if it really changes something. However, it shouldn't change anything, unless there is a heap error somewhere else.

I will check myself as soon as I finish some stuff

**Comment by philbucher** [comment]
I am quite sure, I rebuilt the commits one by one and ran the tests
I agree though that the changes of #8684 should not cause issues, no clue what is happening. Maybe a strange bug? :D

Thx @loumalouomega, I also think it is best if you take a look yourself

**Comment by loumalouomega** [comment]
Probably I am doing something strange when creating new conditions with geometries

**Comment by philbucher** [comment]
this breaks the nightly build for two weeks already, I would say we skip them such that the badge on the main page becomes green again until it could be solved

**Comment by philbucher** [comment]
> this breaks the nightly build for two weeks already, I would say we skip them such that the badge on the main page becomes green again until it could be solved

ping @loumalouomega @AlejandroCornejo

**Comment by loumalouomega** [comment]
I will try to tackle tomorrow, sorry for the delay

**Comment by loumalouomega** [comment]
Good news: I am able to replicate this with an Ubuntu 20.04 machine
Bad news: I don't know exactly why

The tests that fail are Small (which run in the standard CI, and should have been detected in the PR). The only compiler that fails is GCC, but in my local machine with clang 7.5 does not fail, Ubuntu 20.04 considers GCC 9.3

So I don't know which kind of witchcraft is this.

What is the main difference in the compilation with GCC in the standard Ci and the nightly @philbucher ?

**Comment by philbucher** [comment]
nightly uses release, small uses no optimization flags

**Comment by loumalouomega** [comment]
OK, that makes sense as I compiled in Release and as the virtual method removed the optimizations. Good thing is that the tests failing are minimal (2 quadrilaterals), so at least I can take a look in detail easily. I will keep you up to date
