### ISSUE TITLE
Strange bug particular to my machine with tinyexpr function parsing

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#9689]
**Description**
For some reason tinyexpr fails to parse this expression when running RomApplication tests:
```
(0.0)*(50*(exp(t)-1))
```
I've taken some debugging steps that only leave me more confused:
- I've tried it in isolation (just writting a program in C to call tinyexpr) and there is no issue.
- The test passes in my collegues' machines
- The test passes in the CI run
- The test passes if I log onto my machine via ssh form another computer
- I wrote a unit test with this same example and it passes (https://github.com/KratosMultiphysics/Kratos/pull/9688)
- The error occurs both in Release and Debug compilations
- I re-compiled Kratos from scratch and the error persists.

The error is thrown in line 159:
https://github.com/KratosMultiphysics/Kratos/blob/0a14fc33b9587e87df9c9e0f5f28ec1115419bec/kratos/utilities/function_parser_utility.cpp#L157-L160

**Scope**
RomApplication

**To Reproduce**
So far it's only happened in my machine. See Environment for details.
```
cd applications/RomApplication/tests
python3 test_structural_rom.py 
```

**Expected behavior**
The test should pass

**Environment**
- OS: Ubuntu 21.10
- Branch: master
- Python 3.9.7
- Compiled attempted with both:
    -  g++ (Ubuntu 11.2.0-7ubuntu2) 11.2.0
    - Ubuntu clang version 13.0.0-2

**Console output**
```
egomez@PCCB199:~/Work/Kratos/applications/RomApplication/tests$ python3 test_structural_rom.py 
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-dc47ff578d-Debug
Compiled with threading support.
Maximum number of threads: 16.
Process Id: 87369 
Importing    KratosRomApplication 
Initializing KratosRomApplication...
Importing    KratosStructuralMechanicsApplication 
    KRATOS   ___|  |                   |                   |
           \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                 | |   |    |   | (    |   |   | |   (   | |
           _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
Initializing KratosStructuralMechanicsApplication...
[WARNING] ::[MechanicalSolver]:: : Settings contain no longer used setting, please remove it: "problem_domain_sub_model_part_list" 
[WARNING] ::[MechanicalSolver]:: : Settings contain no longer used setting, please remove it: "processes_sub_model_part_list" 
[WARNING] ::[MechanicalSolver]:: : Settings contain no longer used setting, please remove it: "problem_domain_sub_model_part_list" 
[WARNING] ::[MechanicalSolver]:: : Settings contain no longer used setting, please remove it: "processes_sub_model_part_list" 
E..
======================================================================
ERROR: testStructuralDynamicRom2D (__main__.TestStructuralRom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/egomez/Work/Kratos/applications/RomApplication/tests/test_structural_rom.py", line 120, in testStructuralDynamicRom2D
    self.simulation.Run()
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/home/egomez/Work/Kratos/applications/RomApplication/tests/test_structural_rom.py", line 105, in Initialize
    super(type(self.simulation), cls).Initialize()
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_analysis.py", line 42, in Initialize
    super().Initialize()
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/analysis_stage.py", line 89, in Initialize
    self.__CreateListOfProcesses() # has to be done after importing and preparing the ModelPart
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/analysis_stage.py", line 352, in __CreateListOfProcesses
    self._list_of_processes        = self._CreateProcesses("processes", order_processes_initialization)
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/StructuralMechanicsApplication/structural_mechanics_analysis.py", line 83, in _CreateProcesses
    list_of_processes = super()._CreateProcesses(parameter_name, initialization_order)
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/analysis_stage.py", line 317, in _CreateProcesses
    list_of_processes += factory.ConstructListOfProcesses(value) # Does this work? or should it be processes[name]
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/process_factory.py", line 36, in ConstructListOfProcesses
    p = python_module.Factory(item, self.Model)
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/assign_vector_by_direction_to_condition_process.py", line 9, in Factory
    return AssignVectorByDirectionToConditionProcess(Model, settings["Parameters"])
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/assign_vector_by_direction_to_condition_process.py", line 79, in __init__
    super(AssignVectorByDirectionToConditionProcess, self).__init__(Model, settings)
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/assign_vector_by_direction_to_entity_process.py", line 163, in __init__
    self.aux_processes.append( assign_scalar_variable_to_entities_process.AssignScalarVariableToEntitiesProcess(Model, x_params) )
  File "/home/egomez/Work/Kratos/bin/Debug/KratosMultiphysics/assign_scalar_variable_to_entities_process.py", line 93, in __init__
    self.aux_processes.append( KratosMultiphysics.AssignScalarFieldToConditionsProcess(self.model_part, params))
RuntimeError: Error: Parsing error in function: (0.0)*(50*(exp(t)-1))


in kratos/utilities/function_parser_utility.cpp:159:void BasicGenericFunctionUtility::InitializeParser()
   kratos/processes/assign_scalar_field_to_entities_process.cpp:42:AssignScalarFieldToEntitiesProcess<TEntity>::AssignScalarFieldToEntitiesProcess(ModelPart&, Parameters) [with TEntity = Condition]


----------------------------------------------------------------------
Ran 3 tests in 0.179s

FAILED (errors=1)

```

**Comment by rubenzorrilla** [comment]
Could you try compiling with GCC?

**Comment by EduardGomezEscandell** [comment]
> Could you try compiling with GCC?

Sorry, I had it wrong. I compiled it with GCC:
- C: gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
- CXX: g++ (Ubuntu 11.2.0-7ubuntu2) 11.2.0

**Comment by EduardGomezEscandell** [comment]
Same error with Ubuntu clang version 13.0.0-2

**Comment by philbucher** [comment]
I also had issues with this in the sense that it had a weird behavior / interaction with other classes when it shouldn't
This seems to be the same problem as in #9684 (FYI @danielandresarcones)
I am not sure what the problem is, maybe a memory leak (I get some warnings when compiling with Intel, not sure if those are relevant)

@EduardGomezEscandell did you try to run your simple example with valgrind?

**Comment by EduardGomezEscandell** [comment]
No leaks in my small example in C.

For the unit test I have a hard time interpreting it:
[valgrind_log.txt](https://github.com/KratosMultiphysics/Kratos/files/8110282/valgrind_log.txt)

```
LEAK SUMMARY:
==190030==    definitely lost: 7,016 bytes in 34 blocks
==190030==    indirectly lost: 2,151 bytes in 101 blocks
==190030==      possibly lost: 363,954 bytes in 462 blocks
==190030==    still reachable: 7,743,145 bytes in 24,313 blocks
==190030==         suppressed: 0 bytes in 0 blocks
```
There seem to be leaks but I can't quite understand where they are.

**Comment by EduardGomezEscandell** [comment]
I added some more debug info in commit https://github.com/KratosMultiphysics/Kratos/pull/9688/commits/34c540556e7f63f39a8a2ab6de70bb8ebd37007b
```
RuntimeError: Error:  
Parsing error in function: (0.0)*(50*(exp(t)-1))
Error occurred near here :   ^ (char [2])
```

**Comment by EduardGomezEscandell** [comment]
Even wilder discovery:

Running the test from my laptop connecting to my work PC (the one that failed the test) via ssh, the test passes.

**Comment by EduardGomezEscandell** [comment]
The test also passes connecting from the problematic computer to itself with `ssh localhost`.

**Comment by EduardGomezEscandell** [comment]
Well @roigcarlo found the source of the issue.

The problem was my locale. I had it as:
```
locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=es_ES.UTF-8             # <-- This is the relevant bit
LC_TIME=es_ES.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=es_ES.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=es_ES.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=
```

which means that numbers were expected as "0,0" instead of "0.0".

**Comment by EduardGomezEscandell** [comment]
Anyways, the solution was to set my numeric locale to `en_US.UTF-8` and reboot the computer.

Whether this should be necessary or not to run Kratos I guess it's a different issue.
