### ISSUE TITLE
Running a Python Test Script

### ISSUE THREAD

**Issue by mcgicjn2** [KratosMultiphysics/Kratos#9747]
When I use the instructions presented here for debugging tests (https://github.com/KratosMultiphysics/Kratos/wiki/Debugging-Kratos-using-Visual-Studio) and run the debug on a application test script I get the following error:

> Traceback (most recent call last):
>   File "C:\Development\Kratos\Kratos\bin\Debug\applications\GeoMechanicsApplication\tests\test_water_pressure.py", line 4, in <module>
>     import KratosMultiphysics.KratosUnittest as KratosUnittest
>   File "C:\Development\Kratos\Kratos\bin\Debug\KratosMultiphysics\__init__.py", line 19, in <module>
>     from Kratos import *
> ModuleNotFoundError: No module named 'Kratos'

This occurs when simply calling:

> import KratosMultiphysics.KratosUnittest as KratosUnittest

at the start of the test. It clearly find the kratosmultiphysics directory, but can't locate the kratos module from that __init__ script.

FYI I am using Python 3.10

Thanking you in advance for the help.

Regards

Jon

**Comment by mcgicjn2** [comment]
OK, if it helps anyone else. I found that in the debug setup using a python...._d.lib the kratos lib .pyd build is:

 **Kratos_d.cp310-win_amd64.pyd** 

and not **Kratos.pyd**, 

thus the import fails in the **__init__.py**
