### ISSUE TITLE
[CoSim] The PFEM-FEM Example fails 

### ISSUE THREAD

**Issue by VeronikaSinger** [KratosMultiphysics/Kratos#9809]
Hi all,

if I run the PFEM-FEM test in the CoSim App in the current master it fails. Any ideas?
That is the error message:
```
`======================================================================
FAIL: test_PFEM_FEM_water_slide_2d (co_simulation_test_factory.TestCoSimulationCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\x\Documents\software\Kratos\applications\CoSimulationApplication\tests\co_simulation_test_factory.py", line 235, in test_PFEM_FEM_water_slide_2d
    self._runTest()
  File "C:\Users\x\Documents\software\Kratos\applications\CoSimulationApplication\tests\co_simulation_test_case.py", line 33, in _runTest
    CoSimulationAnalysis(self.cosim_parameters).Run()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\analysis_stage.py", line 67, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\CoSimulationApplication\co_simulation_analysis.py", line 84, in FinalizeSolutionStep
    self._GetSolver().FinalizeSolutionStep()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\CoSimulationApplication\coupled_solvers\gauss_seidel_strong.py", line 64, in FinalizeSolutionStep
    super().FinalizeSolutionStep()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\CoSimulationApplication\base_classes\co_simulation_coupled_solver.py", line 193, in FinalizeSolutionStep
    solver.FinalizeSolutionStep()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\CoSimulationApplication\solver_wrappers\kratos\kratos_base_wrapper.py", line 86, in FinalizeSolutionStep
    self._analysis_stage.FinalizeSolutionStep()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\analysis_stage.py", line 149, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "C:\Users\x\Documents\software\Kratos\KratosMultiphysics\from_json_check_result_process.py", line 54, in ExecuteFinalizeSolutionStep
    self.assertTrue(self.process.IsCorrectResult(), "Results do not coincide with the JSON reference\n" + self.process.GetErrorMessage())
AssertionError: False is not true : Results do not coincide with the JSON reference
Error checking for variable DISPLACEMENT_X, results:
Node 17 0!=-0.002125706; rel_tol=1e-06, abs_tol=0.001`

```
Is there any dependency with https://github.com/KratosMultiphysics/Kratos/pull/8525?

**Comment by KlausBSautter** [comment]
Thanks @VeronikaSinger. @ceulogiof this is your test, could you have a look?

**Comment by KlausBSautter** [comment]
`Node 17 0!=-0.002125706; rel_tol=1e-06, abs_tol=0.001`

this looks like some nodes are not properly updated .....

**Comment by philbucher** [comment]
@AFranci @AlejandroCornejo were there updates recently in the pfem app?

**Comment by AlejandroCornejo** [comment]
Hi! As far as I know no changes... @AFranci do you know something? :)

**Comment by ceulogiof** [comment]
Then the only workaround I can think of is to update the `.json` results file, as the test is just to make sure this example is consistently computed. I am currently checking this, and if it solves the issue, I can create a separate PR later. 
As a side note, I had noticed that sometimes if I made a change in the code (e.g. by changing the fixation method via the pfem solver wrapper python script), then later revert it, this benchmark results would be slightly different than the original run, but I always attributed this to randomness in the solution... (I had no other hypothesis of why such a thing would happen).

**Comment by AFranci** [comment]
> Hi! As far as I know no changes... @AFranci do you know something? :)

no recent changes from my side...

**Comment by ceulogiof** [comment]
Hey @VeronikaSinger, I am trying to replicate the error message locally in Linux, but I couldn't. I saw in #8525 that you are running the `test_CoSimulationApplication.py`. My question is, one simply executes the script?

Also, If I set the example separately from the script, using the `from_json_check_result_process`, it seems to be ok.

**Comment by VeronikaSinger** [comment]
Hi @ceulogiof ,
yes, I am executing the `test_CoSimulationApplication.py` with python.
It also seems to fail only in case all necessary applications for the CoSim are compiled.

**Comment by VeronikaSinger** [comment]
Interesting to see - I don't know what change caused the error but it seemed to be a quite strange error as it only appeared in combination with other applications which should be independent...
