### ISSUE TITLE
KratosMultihysics-all ERROR

### ISSUE THREAD

**Issue by LVilla96** [KratosMultiphysics/Kratos#9989]
GOOD DAY!!
When we try to run the GID program, the following error occurs

![image](https://user-images.githubusercontent.com/108200573/175842686-dd7cc5a3-4282-419e-a522-5e58f58e2970.png)

I pressed "yes" and shows the following error report:

Error (l671): Collecting KratosMultiphysics-all
  Downloading KratosMultiphysics_all-9.1.3-py3-none-any.whl (3.6 kB)
ERROR: Could not find a version that satisfies the requirement KratosShallowWaterApplication==9.1.3 (from KratosMultiphysics-all) (from versions: none)
ERROR: No matching distribution found for KratosShallowWaterApplication==9.1.3 (from KratosMultiphysics-all)
STACK:
Collecting KratosMultiphysics-all
  Downloading KratosMultiphysics_all-9.1.3-py3-none-any.whl (3.6 kB)
ERROR: Could not find a version that satisfies the requirement KratosShallowWaterApplication==9.1.3 (from KratosMultiphysics-all) (from versions: none)
ERROR: No matching distribution found for KratosShallowWaterApplication==9.1.3 (from KratosMultiphysics-all)
    while executing
"exec $pip -m pip install --no-cache-dir --disable-pip-version-check {*}$missing_packages"
    (procedure "Kratos::InstallAllPythonDependencies" line 27)
    invoked from within
"Kratos::InstallAllPythonDependencies"
    (procedure "Kratos::CheckDependenciesPipMode" line 28)
    invoked from within
"$deps"
    (procedure "Kratos::CheckDependencies" line 6)
    invoked from within
"Kratos::CheckDependencies"
    (procedure "Kratos::Event_InitProblemtype" line 43)
    invoked from within
"Kratos::Event_InitProblemtype $dir"
    (procedure "::GiD_Event_InitProblemtype" line 2)
    invoked from within
"::GiD_Event_InitProblemtype /home/engineer-user/GiDx64/gid-15.1.6d/problemtypes/kratos.gid"

I appreciate you can help me

**Comment by roigcarlo** [comment]
Hi @LVilla96 

Thx for detecting this. We are working on the fix right now. As soon as it's ready I will ping you (I expect it to be ready during this afternoon / early tomorrow).

Br,

**Comment by MatiasVenegas** [comment]
i have the same problem with linux too.

**Comment by roigcarlo** [comment]
Hi @LVilla96 @MatiasVenegas,

Error should be solved now.
I recommend you to reinstall everything so you don't find any incompatibility:
```bash
pip install --upgrade --force-reinstall --no-cache-dir KratosMultiphysics-all
```

Please tell me if this works for you or it gives you any further error.

**Comment by MatiasVenegas** [comment]
> Hi @LVilla96 @MatiasVenegas,
> 
> Error should be solved now. I recommend you to reinstall everything so you don't find any incompatibility:
> 
> ```shell
> pip install --upgrade --force-reinstall --no-cache-dir KratosMultiphysics-all
> ```
> 
> Please tell me if this works for you or it gives you any further error.

Thanks, it worked.

**Comment by MatiasVenegas** [comment]
@roigcarlo I've another problem with an example of 3D DEM.
When I click on the postprocess label it shows the following warning:
![image](https://user-images.githubusercontent.com/74941380/177692111-e404378b-740d-4aab-9809-fac9fc7a9243.png)

Then shows a warning window with this:
/home/engineer-user/GiDx64/gid-15.1.6d/problemtypes/kratos.gid/exec/pip.unix.bat: línea 13: 310664 Violación de segmento  $kratos_python_exe MainKratos.py > "$2/$1.info" 2> "$2/$1.err"

Sorry, I appreciate you can help me again.

**Comment by roigcarlo** [comment]
I @MatiasVenegas that means the simulation failed. Can you copy the output file (Calculate->View Process Info)?

Also, is this an example that you made or is an already existing example?
Br,

**Comment by roigcarlo** [comment]
Hi @KratosMultiphysics/dem can you help with this? I've tried to reproduce the error in a clean computer and I can confirm it does not work. To me it throws a different error:

```bash
Traceback (most recent call last):
  File "E:\Escritorio\demtest.gid\MainKratos.py", line 31, in <module>
    DEMAnalysisStageWithFlush(global_model, parameters).Run()
  File "C:\Users\roigc\AppData\Roaming\Python\Python39\site-packages\KratosMultiphysics\analysis_stage.py", line 47, in Run
    self.Initialize()
  File "C:\Users\roigc\AppData\Roaming\Python\Python39\site-packages\KratosMultiphysics\DEMApplication\DEM_analysis_stage.py", line 249, in Initialize
    self.ReadModelParts()
  File "C:\Users\roigc\AppData\Roaming\Python\Python39\site-packages\KratosMultiphysics\DEMApplication\DEM_analysis_stage.py", line 458, in ReadModelParts
    self.CheckConsistencyOfElementsAndNodesInEverySubModelPart()
  File "C:\Users\roigc\AppData\Roaming\Python\Python39\site-packages\KratosMultiphysics\DEMApplication\DEM_analysis_stage.py", line 471, in CheckConsistencyOfElementsAndNodesInEverySubModelPart
    ErrorMessage(submp.Name)
  File "C:\Users\roigc\AppData\Roaming\Python\Python39\site-packages\KratosMultiphysics\DEMApplication\DEM_analysis_stage.py", line 462, in ErrorMessage
    raise Exception(" ModelPart (or SubModelPart) "+ name + " has a different number of nodes and elements (particles)! \n")
Exception:  ModelPart (or SubModelPart) DEM-CustomSmp_Body has a different number of nodes and elements (particles)!
```

2D Seems to run ok.

**Comment by roigcarlo** [comment]
Ping @jginternational
